### ISSUE TITLE
Webhook configuration isn't validating correctly

### ISSUE THREAD

**Issue by david-supernormal** [Shopify/shopify-app-js#100]
# Issue summary

After configuring a webhook using shopify-app-express package (as it's configured by default in Shopify Nodejs template), when firing an event, the webhook cannot be validated

-->

- `@shopify/shopify-app-*` package and version: @shopify/shopify-app-express@1.1.0
- Node version: v18.12.1
- Operating system: Ubuntu 22.04.1 LTS running on Windows 11 WSL2

```
[shopify-api/INFO] Processing webhook request | {apiVersion: 2023-01, domain: supernormal-dev.myshopify.com, topic: checkouts/update, webhookId: 
                                 a7762489-908c-4547-85a8-b8c098bfa5a7}
2023-01-24 22:05:16 | backend  | [shopify-app/ERROR] Failed to process webhook: Error: Could not validate request for topic checkouts/update

```

## Expected behavior

When firing an event related with the webhook configured, I should receive the payload

## Actual behavior

Getting a could not validate request error

## Steps to reproduce the problem

1. Configure an express post call for webhooks

`app.post(
  shopify.config.webhooks.path,
  shopify.processWebhooks({ webhookHandlers: webhookHandlerIndex })
);` 

2. Configure the handler as documented by Shopify GDPR examples

`import { DeliveryMethod } from "@shopify/shopify-api";

export const webhookHandlerIndex = () => {

    return ({
        CHECKOUTS_UPDATE: {
            deliveryMethod: DeliveryMethod.Http,
            callbackUrl: "/api/webhooks",
            callback: async (topic, shop, body, webhookId) => {
                const payload = JSON.parse(body);
                console.log(payload)
            }
        },
    })
}
`

**Comment by nzahrir** [comment]
Hi david did you ever figure this out. I am also having trouble configuring the webhooks

**Comment by nzahrir** [comment]
@david-supernormal someone just submitted a bug issue that could be related to why you webhooks aren't validating correctly. The ngrok url might not be updating
