### ISSUE TITLE
[shopify-app-remix] Managed installation and parallel route loading

### ISSUE THREAD

**Issue by zirkelc** [Shopify/shopify-app-js#1057]
# Issue summary

Hi,

I'm not sure if this is strictly a bug or if I simply need some advice how to handle the new managed installation flow correctly. 
I'm using the default remix template created by the Shopify CLI.
After the client has installed the app through managed installation, Shopify redirects the client to the app on route `/app`. Since it's the first request after installation, the `shopifyApp()` starts the *Authenticating admin request* flow and creates a new session and stores it on the session storage. This process is executed multiple times by each `loader()` function matching the current route. In this case, there are two loaders being executed for the request `/app`: 
- `/app/routes/app.tsx` 
- `/app/routes/app._index.tsx`. 

Both loaders run in parallel due to Remix's parallel route loading. Then, after *Authenticating admin request* has finished the `afterAuth()` hook is called. This hook would actually be called twice because of each loader. However, the managed installation via the `TokenExchangeStrategy` dedupes this call so it only runs once:

https://github.com/Shopify/shopify-app-js/blob/7045fe4e3a9c39b858ca8e8337978ee42d496b82/packages/apps/shopify-app-remix/src/server/authenticate/admin/strategies/token-exchange.ts#L159-L172

I use the `afterAuth` hook to create a database entities (user, shop, etc) in my own system. All other authenticated routes need this information and query this API in their respective loaders. Now the problem is that the managed installation through `TokenExchangeStrategy` doesn't provide a sequential authentication flow like with the previous `AuthCodeFlowStrategy`. The authentication in a managed installation seem to be started by multiple loaders in parallel, and the "fastest" loader calls the `afterAuth` hook. That means there are multiple routes rely on the information being created in the `afterAuth` hook but it may not be created **yet**. So I end up with lots of *not found* errors in loaders because they run before the `afterAuth` has finished. The errors disappear after a reload.

My first idea was to throw a redirect at the end of `afterAuth` to force the entire route to reload when the entity was created. But `redirect` is not exposed on the params of `afterAuth` and any error thrown inside `afterAuth` it caught by an outer [`try-catch`](https://github.com/Shopify/shopify-app-js/blob/ed8c30e016d061558dd4321accbcd492524bf569/packages/apps/shopify-app-remix/src/server/authenticate/admin/strategies/token-exchange.ts#L81-L93) anyway.

What is the right way to handle this issue? I think doing API calls inside `afterAuth` after installation sounds like a normal thing, right?

Before opening this issue, I have:

- [X] Upgraded to the latest version of the relevant packages
  - `@shopify/*` package and version:
  - Node version:
  - Operating system:
- [X] Set `{ logger: { level: LogSeverity.Debug } }` in my configuration, when applicable
- [X Found a reliable way to reproduce the problem that indicates it's a problem with the package
- [X] Looked for similar issues in this repository
- [X] Checked that this isn't an issue with a Shopify API
  - If it is, please create a post in the [Shopify community forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) or report it to [Shopify Partner Support](https://help.shopify.com/en/support/partners/org-select)

## Expected behavior

After the managed installation, all loaders should wait for the `afterAuth` hook to be finished before returning.

## Actual behavior

The `-> app.tsx loader` and `-> app._index.tsx loader` are started in parallel. Both loaders start the *Authenticating admin request* flow. The first loaders calls the `-> afterAuth` hook while the second `loader` finishes with `<- app._index.tsx loader` before `<- afterAuth` and `<- app.tsx loader` have finished.

```sh
14:45:48 │ remix         │ [shopify-api/INFO] version 11.0.0, environment Remix
14:45:48 │ remix         │ -> app.tsx loader
14:45:48 │ remix         │ -> app._index.tsx loader
14:45:48 │ remix         │ [shopify-app/INFO] Authenticating admin request
14:45:48 │ remix         │ [shopify-app/INFO] Authenticating admin request
14:45:48 │ remix         │ [shopify-app/INFO] No valid session found
14:45:48 │ remix         │ [shopify-app/INFO] Requesting offline access token
14:45:48 │ remix         │ [shopify-app/INFO] No valid session found
14:45:48 │ remix         │ [shopify-app/INFO] Requesting offline access token
14:45:49 │ remix         │ [shopify-api/INFO] Creating new session | {shop: nebula-etl-test.myshopify.com, isOnline: false}
14:45:49 │ remix         │ [shopify-app/INFO] Running afterAuth hook
14:45:49 │ remix         │ -> afterAuth
14:45:49 │ remix         │ Creating user
14:45:49 │ remix         │ [shopify-api/INFO] Creating new session | {shop: nebula-etl-test.myshopify.com, isOnline: false}
14:45:49 │ remix         │ <- app._index.tsx loader
14:45:49 │ remix         │ No user found
14:45:50 │ remix         │ User created
14:45:50 │ remix         │ [shopify-api/INFO] Registering webhooks | {shop: nebula-etl-test.myshopify.com}
14:45:50 │ remix         │ <- afterAuth
14:45:50 │ remix         │ <- app.tsx loader
```

## Steps to reproduce the problem

Repo: https://github.com/zirkelc/shopify-managed-installation

`pnpm shopify app dev`

**Comment by paulomarg** [comment]
>After an app was approved to be installed via the managed installation flow, Shopify redirects the merchant to the app. What is the target URL after in this case? I assume it's the application_url in the shopify.app.toml (same asappUrl on shopifyApp()), right?

Right!

> The route (and loader) which is active on this application_url route must authenticate the request and trigger the afterAuth hook to create the user in the database. Then, its should redirect to any other routes that assumes the user already exists. So the key is that only one route (loader) after installation is active.

Right again. What happens here is that the template runs 2 `loader`s in this case - one in `routes/app._index.tsx`, and one in `routes/app.tsx` - the second one is a [Remix layout](https://remix.run/docs/en/main/discussion/routes#conventional-route-configuration) that is run for every route under `routes/app.*.tsx`.

What I meant was that you don't _need_ to have a layout, so you could for instance delete `routes/app.tsx`, and the routing would still work, and only the loader in `routes/app._index.tsx` would be run.

That would probably solve the problem you're having with 2 loaders running for that action. The downside is that you would need to replicate the code from `routes/app.tsx` in every route in `routes/app.*.tsx` for `authenticate.admin` to work properly.

Hope that made it a little clearer!

> On a sidenote, what is the purpose of the _index/route.tsx and who calls this route?

This is a landing / marketing page that you can customize however you want, if you want to show it to users to encourage them to try the app / other features that aren't app related. You can reach it by visiting `https://<your-app-url>` directly from the browser :)

**Comment by zirkelc** [comment]
Thanks again for the quick reply, I got it! :) I will try that out and see how it works. 

I have two alternative ideas and I'd like to hear your opinion on them:

- each `loader` receives the current `session` from `authenticate.admin`.  let's say there is a session (e.g. created in the last 60 seconds) but no existing `user` yet, that could mean the `user` is just being created by another `loader`. to solve this issue, I could just throw a `redirect` to trigger a reload of the current URL. I would just need to know the current URL / route somehow. Do you know if there is a way to get this information?

---

- when `afterAuth()` runs, it could throw a `Response` in order to redirect the user to some kind of post-installation route (e.g. to show a welcome message, intro, etc) or to simply trigger a refresh of the current URL and routes. This is currently not possible because the thrown object from `afterAuth` is swallowed by this try-catch:
https://github.com/Shopify/shopify-app-js/blob/ed8c30e016d061558dd4321accbcd492524bf569/packages/apps/shopify-app-remix/src/server/authenticate/admin/strategies/token-exchange.ts#L81-L93
Wouldn't it make sense to allow the `Response` to **bubble up** so we have more flexibility of what happens post-auth? I know this try-catch block is embedded in the `authenticate` that is supposed to return a `session`, so this feature would require some kind of re-write to make it work. On the other side, it looks like `authenticate` is being called by the `authStrategyFactory` here:
https://github.com/Shopify/shopify-app-js/blob/ed8c30e016d061558dd4321accbcd492524bf569/packages/apps/shopify-app-remix/src/server/authenticate/admin/authenticate.ts#L137-L155
This function `authStrategyFactory.authenticateAdmin()` lets a possible `Error` or `Response`  bubble up, so if `authenticate` would return a `session` and/or a `Response` it could just be re-thrown here.

**Comment by zirkelc** [comment]
That would be great! Sure, I'll be happy to work on this and submit a PR in the next few days. 

Thanks for your support!

**Comment by zirkelc** [comment]
Hi @minhduc17801 your code looks fine, did you test it locally? Are you using managed installation oder OAuth?

**Comment by minhduc17801** [comment]
Hi @zirkelc , thank you for your response, and I also apologize for my delay. I am using the default managed installation from the Remix template. I have also added logs and made some adjustments to the code in my previous comment; you can review it. I have tested it locally, and here are some results from my tests.

1. If I throw a redirect response in afterAuth, it seems that the response lacks headers or queries for authentication, and I keep getting redirected to /auth/login
![Image](https://github.com/user-attachments/assets/f9a4e280-3d39-4bff-9e45-d15bb7ad99bb)


2.If I don't return a response in afterAuth, as you mentioned above, both loaders will be called, and both authenticate.admin will run, but only one will wait for afterAuth. The other will skip authentication and continue executing the code below, encountering my conditional logic and throwing a 500 server error. However, it seems that the app.tsx loader is called again every time afterAuth finishes. So, if afterAuth is triggered by app._index.tsx, my application works fine, but if it’s triggered by app.tsx, it will encounter a 500 server error.

  -afterAuth run in app.tsx loader, app crash with 500 server error
![Image](https://github.com/user-attachments/assets/889a3552-89a1-4c79-9c1d-75c79b36c542)

  -afterAuth run in app._index.tsx loader, app works fine.
![Image](https://github.com/user-attachments/assets/e53b38f4-3240-462e-95dc-806258580d0c)

I think the simplest solution would be to make redirect response from afterAuth pass through authenticate and potentially trigger a reload of app.tsx and app._index.tsx. However, due to my lack of experience with both coding and Shopify, I haven't been able to implement it successfully. I would really appreciate your help with this. Thank you!
