### ISSUE TITLE
[Billing] Return all fields from AppSubscription mutation

### ISSUE THREAD

**Issue by zirkelc** [Shopify/shopify-app-js#1064]
## Overview

The current billing API ob `shopify-api` and `shopify-app-remix` only return a subset of the fields of [`AppSubscription`](https://shopify.dev/docs/api/admin-graphql/2024-04/objects/AppSubscription) object.

For example, `billing.cancel` returns: `id, name, test`
https://github.com/Shopify/shopify-app-js/blob/ed8c30e016d061558dd4321accbcd492524bf569/packages/apps/shopify-api/lib/billing/cancel.ts#L7-L21

The `AppSubscription` type also defines only this subset of fields:
https://github.com/Shopify/shopify-app-js/blob/ed8c30e016d061558dd4321accbcd492524bf569/packages/apps/shopify-api/lib/billing/types.ts#L320-L338

What is missing is, for example, the [`currentPeriodEnd `](https://shopify.dev/docs/api/admin-graphql/2024-04/objects/AppSubscription#field-appsubscription-currentperiodend) to know when the app subscription actually ends. 
It looks like the Billing Admin GraphQL API doesn't provide any `query` operation to get information about the current app subscription, so the returned object from `billing.cancel` is the only way to know when the subscription ends. 

I'd like to suggest to add all fields of `AppSubscription` to the returned object of `billing.cancel` and `billing.check`, or alternatively add an optional param to enable to return the complete object.

**Comment by matteodepalo** [comment]
Hi @zirkelc thank you for opening this, the suggestion makes sense, I'll put this item in our backlog.

> It looks like the Billing Admin GraphQL API doesn't provide any query operation to get information about the current app subscription, so the returned object from billing.cancel is the only way to know when the subscription ends.

Is the `activeSubscriptions` field in https://shopify-dev-staging4.shopifycloud.com/docs/api/admin-graphql/2024-04/queries/currentAppInstallation not useful in this case?

**Comment by zirkelc** [comment]
Hi @matteodepalo thank you for the quick response!

I literally stumbled upon this query after I have already opened this issue. The billing APIs use this query under the hood, so I could simply use this query as well. It would be nicer if I wouldn't need to sue the graphql client for this and billing would return these fields (the complete AppSubscription object), but this is just my personal preferences. 

Let me know if you consider it, otherwise feel free to close this issue.

**Comment by matteodepalo** [comment]
Hi @zirkelc, great to hear that you can use that query! I understand the inconvenience this might cause, but I'm going to close this issue for now. We can reconsider re-opening it if there is strong necessity to add these fields here too.
