### ISSUE TITLE
Theme Rest Resource doesn't have `fromData` applied automatically

### ISSUE THREAD

**Issue by david-w-shopify** [Shopify/shopify-app-js#1086]
# Issue summary

Before opening this issue, I have:

- [x] Upgraded to the latest version of the relevant packages
  - `@shopify/shopify-api` package and version: 11.0.1
  - `@shopify/shopify-app-remix` package and version: 3.0.1
  - Node version: 21.7.1
  - Operating system: macOS Sonoma 14.5
- [x] Found a reliable way to reproduce the problem that indicates it's a problem with the package
- [x] Looked for similar issues in this repository
- [x] Checked that this isn't an issue with a Shopify API

`Theme` rest resource no longer has `fromData` applied to it. I suspect this is happening with other rest resources too, but it's only impacted me with themes.

Using this snippet

```ts
const { admin, session } =  await authenticate.admin(request);
const theme = new admin.rest.resources.Theme({
  session,
  fromData: {
    name: 'Test',
    src: 'test',
    role: 'unpublished'
  }
});

console.log({ theme })
```

## Expected behavior

Using the above snippet I'd expect this to be logged:

```js
{
    theme: Theme {
    name: 'Test',
    src: 'test',
    role: 'unpublished',
    created_at: undefined,
    id: undefined,
    previewable: undefined,
    processing: undefined,
    theme_store_id: undefined,
    updated_at: undefined
  }
}
```

## Actual behavior

I get this

```js
{
    theme: Theme {
    name: undefined,
    src: undefined,
    role: undefined,
    created_at: undefined,
    id: undefined,
    previewable: undefined,
    processing: undefined,
    theme_store_id: undefined,
    updated_at: undefined
  }
}
```

## Steps to reproduce the problem

I've created this repo to reproduce the issue: https://github.com/david-w-shopify/shopify-rest-resource-issue.

1. Clone the above repo and install dependencies (if you'd rather set it up yourself, just create a new remix app via the cli) and copy from `app/routes/app.tsx` the reproduction repo
2. Run `pnpm dev` and install the app on a test store
3. Visit the app in your store
4. Check the console to see the `theme` variable being logged

**Comment by matthew-charles-chan** [comment]
I have found the same behaviour with `Orders`. 

Using this snippet:
```js
  const { admin, session } = await authenticate.admin(request);

  const orderData = {
    email: "foo@example.com",
    fulfillment_status: "fulfilled",
    fulfillments: [
      {
        location_id: 24826418,
      },
    ],
    line_items: [
      {
        variant_id: 447654529,
        quantity: 1,
      },
    ],
  };

  const order = new admin.rest.resources.Order({
    session,
    fromData: orderData,
  });

  await order.save({ update: true });
  
```

### Expected Behaviour
A new order will be created without error.

### Actual Behaviour
A 400 error is thrown:
```js
errors: { order: 'Required parameter missing or invalid' }
```

**Comment by matteodepalo** [comment]
Thank you for reporting this @david-w-shopify, we'll take a look.

**Comment by NirvanaNrv** [comment]
I got the same thing with Webhook. Logging in the constructor of Base showed me a correctly updated 'this' from 'fromData' right before exiting. Commenting the field block at the end of webhook.mjs made it work properly. And that is the length of my analysis on this. Note fromData was working for me a few months ago.

**Comment by andy-liuu** [comment]
Hi folks,

We do not plan on addressing this issue. The REST Admin API is a legacy API as of October 1, 2024. All apps and integrations should be built with the [GraphQL Admin API](https://shopify.dev/docs/api/admin-graphql).

If you have any other problems with our libraries related to themes, webhooks, or anything else, please create a new issue.

For more information, please read this blog post: https://www.shopify.com/ca/partners/blog/all-in-on-graphql
