### ISSUE TITLE
Regions in Customer Privacy cannot be unchecked after using consentPolicyUpdate API

### ISSUE THREAD

**Issue by GrigorBorisov97** [Shopify/shopify-app-js#1103]
# Issue summary
We have implemented GraphQL to update customer privacy regions using the following query:
`$query = json_encode([
            "query" => 'mutation consentPolicyUpdate($consentPolicies: [ConsentPolicyInput!]!) {
                consentPolicyUpdate(consentPolicies: $consentPolicies) {
                    updatedPolicies {
                        id
                        consentRequired
                        countryCode
                        dataSaleOptOutRequired
                        regionCode
                        shopId
                    }
                    userErrors {
                        field
                        message
                    }
                }
            }',
            "variables" => [
                "consentPolicies" => [
                    [ "countryCode" => "BG", "dataSaleOptOutRequired" => true, "consentRequired" => true, "regionCode" => "BG01" ]
                ]
            ]
        ]);`
        
We are using the "unstable" API version because the endpoint is not present in the 2024-04 and 2024-07 versions.

After using the API, the countries are added to the regions in Customer Privacy as expected. However, the regions cannot be unchecked once added.

I have attached a recording showcasing the issue [Recording](https://monosnap.com/direct/RO0PUvmGwFefhGhECyOexispatlZBs) .

Is there any technical guidance or solution you can provide for this issue?

**Comment by matteodepalo** [comment]
Hi @GrigorBorisov97, this seems to be an issue with the API/dashboard and not with the client libraries which this repo represents for JS. May I suggest you open a support request and/or a community post [here](https://community.shopify.com/c/partners-and-developers/ct-p/appdev)? Thank you!
