### ISSUE TITLE
Proxy from toml not updating on store app.

### ISSUE THREAD

**Issue by lawrencetaur** [Shopify/shopify-app-js#1122]
# Issue summary

Before opening this issue, I have:

- [x] Upgraded to the latest version of the relevant packages
  - `@shopify/*` package and version: 
  - Node version: 20.14.0
  - Operating system: MacOS Sonoma 14.5
- [x] Set `{ logger: { level: LogSeverity.Debug } }` in my configuration, when applicable
- [x] Found a reliable way to reproduce the problem that indicates it's a problem with the package
- [x] Looked for similar issues in this repository
- [x] Checked that this isn't an issue with a Shopify API
  - If it is, please create a post in the [Shopify community forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) or report it to [Shopify Partner Support](https://help.shopify.com/en/support/partners/org-select)

I have been trying to send a proxy requests from /apps/proxy to a route on my Shopify Remix app. it worked initially.

I then changed the subpath in shopify.app.toml. This updated the setting in the partners dashboard correctly. However, it did not update correctly on the development store 
## Expected behavior
It should update the subpath for the app on the store as well. 
The store may have /apps/proxy but If I change it in the app settings to /apps/proxy1 or /apps/carrier, it does not update on the store. 

## Actual behavior
The sub path does not update on the store, not sure why it can't fetch the sub path from the app settings but has its own copy of the path. 

What actually happens?

## Steps to reproduce the problem

1. create proxy in sopify.app.toml add the following settings
`[app_proxy]
url = "https://domain.com/apps/proxy"
subpath = "carrier"
prefix = "apps"`
2. test the proxy hitting your endpoint, it should work. storeurl.com/apps/proxy will work well.
3. now change the proxy url to
`[app_proxy]
url = "https://domain.com/apps/carrier"
subpath = "carrier"
prefix = "apps"`
This will update correctly in the partners dashboard under app settings. but when you visit storeurl.com/apps/carrier it will return a 404.

**Comment by matteodepalo** [comment]
Hi @lawrencetaur, thank you for opening this issue. What happens if you re-install the app on the store, does the URL get updated?

**Comment by oribenez** [comment]
Is there any planing on fixing it?
