### ISSUE TITLE
@shopify/api-codegen-preset 1.0.1: introspectionResult.errors.map is not a function / 

### ISSUE THREAD

**Issue by florianbepunkt** [Shopify/shopify-app-js#1128]
# Issue summary

Before opening this issue, I have:

- [x ] Upgraded to the latest version of the relevant packages
  - `@shopify/*` package and version: @shopify/api-codegen-preset 1.0.1
  - Node version: 20
  - Operating system: MacOS
- [x] Set `{ logger: { level: LogSeverity.Debug } }` in my configuration, when applicable
- [x] Found a reliable way to reproduce the problem that indicates it's a problem with the package
- [x] Looked for similar issues in this repository
- [x] Checked that this isn't an issue with a Shopify API
  - If it is, please create a post in the [Shopify community forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) or report it to [Shopify Partner Support](https://help.shopify.com/en/support/partners/org-select)

Using the @shopify/api-codegen-preset throws an error during type generation: `introspectionResult.errors.map is not a function`. This might be caused by https://shopify.dev/admin-graphql-direct-proxy/2023-10 (from the docs config) returning a 404.

## Expected behavior

I should be able to reproduce the example from the docs: https://shopify.dev/docs/api/shopify-app-remix/v3/guide-graphql-types

## Actual behavior

What actually happens?

```
✔ Parse Configuration
⚠ Generate outputs
  ❯ Generate to ./src/types/admin-2023-10.schema.json
    ✖ introspectionResult.errors.map is not a function
    ◼ Load GraphQL documents
    ◼ Generate
```

## Steps to reproduce the problem

Follow the docs https://shopify.dev/docs/api/shopify-app-remix/v3/guide-graphql-types

**Comment by storz** [comment]
I'm encountering the same issue.

> This might be caused by https://shopify.dev/admin-graphql-direct-proxy/2023-10 (from the docs config) returning a 404.

The endpoint likely exists and returns a non-404 response to a POST request (although this doesn't provide information to solve the problem)
```sh
$ curl -X POST https://shopify.dev/admin-graphql-direct-proxy/2023-10
{"errors":{"query":"Required parameter missing or invalid"}}%
```

Additionally, the same situation occurs when changing the version to 2024-01, 2024-04, or 2024-07 (unstable).

**Comment by chenaski** [comment]
I can confirm the same error. I wasn't able to identify the exact reason, but it probably happened after packages update.

The current workaround I found is to use your shop's API directly: `https://${STORE_DOMAIN}/admin/api/${API_VERSION}/graphql.json` instead of using `https://shopify.dev/admin-graphql-direct-proxy`.

<details>
<summary>Here's the full version of our `codegen.ts` file, might be useful for someone</summary>

```typescript
import type {CodegenConfig} from '@graphql-codegen/cli';
import {getSchema, pluckConfig, preset} from '@shopify/hydrogen-codegen';
import {ApiType} from '@shopify/api-codegen-preset';

const outputDir = './app/generated';
const queriesDir = './app/graphql';

const STORE_DOMAIN = '';
const ACCESS_TOKEN = '';
const API_VERSION = '2024-04';
const adminSchema: CodegenConfig['schema'] = {
  [`https://${STORE_DOMAIN}/admin/api/${API_VERSION}/graphql.json`]: {
    headers: {'X-Shopify-Access-Token': ACCESS_TOKEN},
  },
};
const storefrontDocuments = ['./app/**/*.{ts,tsx}', `!${outputDir}`, `!${queriesDir}/**`];
const customerAccountDocuments = `${queriesDir}/customer-account/*.ts`;
const adminDocuments = [`${queriesDir}/admin-api/*.ts`];
const migrationDocuments = './migrations/**/*.ts';

export default {
  overwrite: true,
  pluckConfig: pluckConfig as CodegenConfig['pluckConfig'],
  generates: {
    [`${outputDir}/storefrontapi.generated.d.ts`]: {
      preset,
      schema: getSchema('storefront'),
      documents: storefrontDocuments,
    },

    [`${outputDir}/customeraccountapi.generated.d.ts`]: {
      preset,
      schema: getSchema('customer-account'),
      documents: customerAccountDocuments,
    },

    [`${outputDir}/admin.schema.json`]: {
      schema: adminSchema,
      documents: adminDocuments,
      plugins: ['introspection'],
      config: {minify: true},
    },

    [`${outputDir}/admin.types.d.ts`]: {
      schema: adminSchema,
      documents: adminDocuments,
      plugins: ['typescript'],
    },

    [`${outputDir}/admin.generated.d.ts`]: {
      schema: adminSchema,
      documents: adminDocuments,
      preset,
      presetConfig: {
        apiType: ApiType.Admin,
        apiVersion: '2024-04',
      },
    },

    [`${outputDir}/admin.sdk.ts`]: {
      schema: adminSchema,
      documents: adminDocuments,
      preset: 'import-types',
      presetConfig: {
        typesPath: './admin.generated',
        importTypesNamespace: 'Operations',
      },
      plugins: ['typescript-generic-sdk'],
      config: {
        importOperationTypesFrom: 'Operations',
      },
    },

    [`${outputDir}/migrations.generated.d.ts`]: {
      schema: adminSchema,
      documents: migrationDocuments,
      preset,
      presetConfig: {
        apiType: ApiType.Admin,
        apiVersion: '2024-04',
      },
    },
  },
} satisfies CodegenConfig;
```
</details>

**Comment by skelouse** [comment]
https://shopify.dev/admin-graphql-direct-proxy/2024-04 is returning a 200:

```json
{ errors: 'Not Found' }
```

Here's a curl to get the same error:

```sh
curl -X POST 'https://shopify.dev/admin-graphql-direct-proxy/2024-04' \
-H 'Accept: application/graphql-response+json, application/json, multipart/mixed' \
-H 'Content-Type: application/json' \
-d '{"query":"query IntrospectionQuery {\\n  __schema {\\n    queryType {\\n      name\\n    }\\n    mutationType {\\n      name\\n    }\\n    subscriptionType {\\n      name\\n    }\\n    types {\\n      ...FullType\\n    }\\n    directives {\\n      name\\n      description\\n      locations\\n      args {\\n        ...InputValue\\n      }\\n    }\\n  }\\n}\\n\\nfragment FullType on __Type {\\n  kind\\n  name\\n  description\\n  fields(includeDeprecated: true) {\\n    name\\n    description\\n    args {\\n      ...InputValue\\n    }\\n    type {\\n      ...TypeRef\\n    }\\n    isDeprecated\\n    deprecationReason\\n  }\\n  inputFields {\\n    ...InputValue\\n  }\\n  interfaces {\\n    ...TypeRef\\n  }\\n  enumValues(includeDeprecated: true) {\\n    name\\n    description\\n    isDeprecated\\n    deprecationReason\\n  }\\n  possibleTypes {\\n    ...TypeRef\\n  }\\n}\\n\\nfragment InputValue on __InputValue {\\n  name\\n  description\\n  type {\\n    ...TypeRef\\n  }\\n  defaultValue\\n}\\n\\nfragment TypeRef on __Type {\\n  kind\\n  name\\n  ofType {\\n    kind\\n    name\\n    ofType {\\n      kind\\n      name\\n      ofType {\\n        kind\\n        name\\n        ofType {\\n          kind\\n          name\\n          ofType {\\n            kind\\n            name\\n            ofType {\\n              kind\\n              name\\n              ofType {\\n                kind\\n                name\\n                ofType {\\n                  kind\\n                  name\\n                  ofType {\\n                    kind\\n                    name\\n                  }\\n                }\\n              }\\n            }\\n          }\\n        }\\n      }\\n    }\\n  }\\n}"}'
```

**Comment by anhdd-kuro** [comment]
Same here ! I think this's kind of critical and need fix asap

**Comment by suryarajendhran** [comment]
Facing the same issue with the remix app example.

**Comment by junyuanxue** [comment]
Same here, would appreciate some 👀 and 🔧 from Shopify! 🙏

**Comment by nathanerwin** [comment]
Getting same issue! Definitely needs to be addressed ASAP!

**Comment by mkromann** [comment]
Same issue here.

**Comment by matteodepalo** [comment]
Hi @florianbepunkt, thank you for opening this issue, the team is taking a look now.

**Comment by xqwtsz** [comment]
same issue here, tried different api versions and also package versions, problem persists.

**Comment by noahub** [comment]
It looks like this may be resolved now @matteodepalo? I'm now able to generate my types as expected.

**Comment by nathanerwin** [comment]
This is still open for admin api codegen schema and types

**Comment by matteodepalo** [comment]
Thank you everyone for your patience. As @skelouse pointed our we've resolved the issue. Please feel free to open a new one if you experience problems with api-codegen-preset.
