### ISSUE TITLE
Error on running development server after installing latest version.

### ISSUE THREAD

**Issue by Ulset** [Shopify/shopify-app-js#1169]
# Issue summary

Before opening this issue, I have:

- [x] Upgraded to the latest version of the relevant packages
  - `@shopify/*` package and version:
  - Node version:
  - Operating system:
- [ ] Set `{ logger: { level: LogSeverity.Debug } }` in my configuration, when applicable
- [x] Found a reliable way to reproduce the problem that indicates it's a problem with the package
- [x] Looked for similar issues in this repository
- [x] Checked that this isn't an issue with a Shopify API
  - If it is, please create a post in the [Shopify community forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) or report it to [Shopify Partner Support](https://help.shopify.com/en/support/partners/org-select)

After updated the `@shopify/shopify-app-remix` package to the next major version (3). I cant start the app with `npm run dev` anymore. I get the following error:

<img width="1245" alt="bilde" src="https://github.com/Shopify/shopify-app-js/assets/33099664/4eee87df-494d-417c-b9b7-0f179d37c8e3">

Downgrading to version 2.8.0 solves the error.

## Expected behavior
Being able to start the app

## Actual behavior
Not being able to start

## Steps to reproduce the problem
1. Install latest version
2. run the `npm run dev` command

## Debug logs
19:45:57 │                   remix │
19:45:57 │                   remix │  info  building...
19:45:57 │        theme-extensions │
19:45:57 │        theme-extensions │ --------- Pushing theme files to App Ext. Host (5cb84c-Sanders-MacBook-Pro) (#134943277194) on weebe-testing.myshopify.com
19:45:57 │        theme-extensions │ Pushing theme...     0%
19:45:58 │ weebe-discount-function │ Done!
19:45:58 │                   remix │ ✘ [ERROR] Expected ";" but found "with"
19:45:58 │                   remix │
19:45:58 │                   remix │     node_modules/@shopify/shopify-app-remix/dist/esm/react/components/AppProvider/AppProvider.mjs:3:59:
19:45:58 │                   remix │       3 │ ...I18n from '@shopify/polaris/locales/en.json' with { type: 'json' };
19:45:58 │                   remix │         │                                                 ~~~~
19:45:58 │                   remix │         ╵                                                 ;
19:45:58 │                   remix │
19:45:58 │                   remix │

**Comment by lizkenyon** [comment]
Hi there 👋 

You may have noticed that we have dropped support for Node 16, and added support for Node 22 in the latest version.

You will need to be on one of the following Node versions.
```
{"node":"^18.20 || ^20.10 || >=21.0.0"}
```

**Comment by lizkenyon** [comment]
Sorry to clarify.

To support Node 22, we needed to drop Node 16. As well as limit the other versions to support import attributes. This is a feature that replaced import assertions, but had to be patched into later versions of Node 18 and 20.

So you will need to be on of of the following Node versions
```
{"node":"^18.20 || ^20.10 || >=21.0.0"}
```

**Comment by estoylive** [comment]
this is not true, i had node 20+ and got the same error... downgraded to 18... same error... what is going on?

**Comment by estoylive** [comment]
NODE 22 ALSO FAILS... WHAT THE HECK MAN.
