### ISSUE TITLE
Error on running development server after installing latest version.

### ISSUE THREAD

**Issue by Ulset** [Shopify/shopify-app-js#1192]
# Issue summary

Before opening this issue, I have:

- [x] Upgraded to the latest version of the relevant packages
  - `@shopify/*` package and version:
  - Node version:
  - Operating system:
- [ ] Set `{ logger: { level: LogSeverity.Debug } }` in my configuration, when applicable
- [x] Found a reliable way to reproduce the problem that indicates it's a problem with the package
- [x] Looked for similar issues in this repository
- [x] Checked that this isn't an issue with a Shopify API
  - If it is, please create a post in the [Shopify community forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) or report it to [Shopify Partner Support](https://help.shopify.com/en/support/partners/org-select)

After updated the `@shopify/shopify-app-remix` package to the next major version (3). I cant start the app with `npm run dev` anymore. I get the following error:

<img width="1245" alt="bilde" src="https://github.com/Shopify/shopify-app-js/assets/33099664/4eee87df-494d-417c-b9b7-0f179d37c8e3">

Downgrading to version 2.8.0 solves the error.

I orignally submitted this issue a few days ago, but you guys closed it with this comment: https://github.com/Shopify/shopify-app-js/issues/1169#issuecomment-2214850276

I am currently using node version 21.7.2

## Expected behavior
Being able to start the app

## Actual behavior
Error on startup

## Steps to reproduce the problem
1. Install latest version
2. run the `npm run dev` command

## Debug logs
19:45:57 │                   remix │
19:45:57 │                   remix │  info  building...
19:45:57 │        theme-extensions │
19:45:57 │        theme-extensions │ --------- Pushing theme files to App Ext. Host (5cb84c-Sanders-MacBook-Pro) (#134943277194) on weebe-testing.myshopify.com
19:45:57 │        theme-extensions │ Pushing theme...     0%
19:45:58 │ weebe-discount-function │ Done!
19:45:58 │                   remix │ ✘ [ERROR] Expected ";" but found "with"
19:45:58 │                   remix │
19:45:58 │                   remix │     node_modules/@shopify/shopify-app-remix/dist/esm/react/components/AppProvider/AppProvider.mjs:3:59:
19:45:58 │                   remix │       3 │ ...I18n from '@shopify/polaris/locales/en.json' with { type: 'json' };
19:45:58 │                   remix │         │                                                 ~~~~
19:45:58 │                   remix │         ╵                                                 ;
19:45:58 │                   remix │
19:45:58 │                   remix │

**Comment by einzN** [comment]
same issue here, prob related #1031

**Comment by Ulset** [comment]
As stated in the issue, im on node version 21.7.2 which would be '>=21.0.0'

**Comment by Ulset** [comment]
Yes, and as stated in the issue im on node 21.7.2. Isnt my version supported since its '>=21.0.0'?

**Comment by Ulset** [comment]
Tried upgrading node
<img width="578" alt="bilde" src="https://github.com/user-attachments/assets/f0a3fe83-9dd4-4630-80d2-03b64aa26e00">

Still facing the same issue
<img width="578" alt="bilde" src="https://github.com/user-attachments/assets/3842c73e-4dd8-4770-b2eb-fd696e5a8381">

Guess youre right @einzN, but i dont understand how this isnt a bigger issue for other people. Shouldt this be a critical bug for all users?

**Comment by lizkenyon** [comment]
This is tricky because I cannot reproduce this. 

You would expect to get this error if you were on an Node version that did not support import attributes, but I do see your print out of the version that should be working.

It almost seems like your app is using a different version of Node, then what is being shown. Are you using `nvm` to switch your versions? Something else?


<img width="759" alt="image" src="https://github.com/user-attachments/assets/20a2af63-f9d2-499d-b4fc-4aa4fc5f777c">

<img width="1552" alt="image" src="https://github.com/user-attachments/assets/6e60bcc2-cf02-46f3-a190-3b98dc2f1b55">

**Comment by RubenRodrigo** [comment]
@Ulset I was facing the same issue while trying to migrate from remix.config to vite. I've update the shopify.web.toml -> commands part like this:

from:
```
[commands]
dev = "npm exec remix dev"
```
to:

```
[commands]
predev = "npx prisma generate"
dev = "npx prisma migrate deploy && npm exec remix vite:dev"

```

**Comment by Ulset** [comment]
Ive sucessfully managed to convert to vite and that solves my issue. I didnt know that vite was required to use v3. Thanks for the help guys <3
