### ISSUE TITLE
i18n import with type in AppProvider causes deployment to fail

### ISSUE THREAD

**Issue by s-prestele-tqgg** [Shopify/shopify-app-js#1256]
# Issue summary

Before opening this issue, I have:

- [x] Upgraded to the latest version of the relevant packages
  - `@shopify/*` package and version:
  - Node version: 22
  - Dockerfile with node: 22-slim
- [ ] Set `{ logger: { level: LogSeverity.Debug } }` in my configuration, when applicable
- [x] Found a reliable way to reproduce the problem that indicates it's a problem with the package
- [x] Looked for similar issues in this repository
- [ ] Checked that this isn't an issue with a Shopify API
  - If it is, please create a post in the [Shopify community forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) or report it to [Shopify Partner Support](https://help.shopify.com/en/support/partners/org-select)

We have upgraded to Node22 and the latest version of shopify-app-remix, this works fine locally when using the CLI, however, fails to deploy to production in CI. 

The error can be seen here: 
![Bildschirmfoto 2024-07-24 um 14 37 41](https://github.com/user-attachments/assets/b04bf4e1-1037-4831-a696-3cda9b4f190a)

[File in question](https://github.com/Shopify/shopify-app-js/blob/28122e6f74c73bd509c23a14ae8c0212fa839691/packages/shopify-app-remix/src/react/components/AppProvider/AppProvider.tsx#L8)

it was also [described here](https://github.com/Shopify/shopify-app-template-remix/issues/692#issuecomment-2156153717)

**Comment by Arkham** [comment]
Hey @s-prestele-tqgg,

thanks for reporting this. I can see that the error comes from `pnpm install`. Could you try specifying `use-node-version=YOUR_NODE_VERSION` inside your `.npmrc`?

**Comment by Arkham** [comment]
can you verify that on the production environment you're using the same version of node and pnpm that you're using locally? I also saw [this bug](https://github.com/pnpm/pnpm/issues/6981) that related to pnpm and workspaces, something you might want to investigate.

**Comment by s-prestele-tqgg** [comment]
> can you verify that on the production environment you're using the same version of node and pnpm that you're using locally? I also saw [this bug](https://github.com/pnpm/pnpm/issues/6981) that related to pnpm and workspaces, something you might want to investigate.

Yes, both locally and during production build the same node and pnpm versions are being used. i also tried with pnpm 8 and 9 and the result is the same.

**Comment by NguyenQuangHuy282002** [comment]
I've upgraded to the latest version of shopify-app-remix and facing this issue too. I use remix build to build app. May be we should try using Vite to build instead.

**Comment by s-prestele-tqgg** [comment]
@nullndr thanks! currently still in the process of migrating to Vite. But hopefully this will resolve once it's completed

**Comment by nullndr** [comment]
@s-prestele-tqgg do you have other issues?

**Comment by s-prestele-tqgg** [comment]
This was indeed resolved when migrating from classic remix compiler to vite. Therefore closing the issue
