### ISSUE TITLE
@shopify/api-codegen-preset is not working at all for me

### ISSUE THREAD

**Issue by aurelienbobenrieth** [Shopify/shopify-app-js#1338]
# Issue summary

Before opening this issue, I have:

- [x] Upgraded to the latest version of the relevant packages
  - `"@shopify/admin-api-client": "^1.0.1"`
  - `"@shopify/api-codegen-preset": "^1.0.1"`
  - Node version: v22.3.0
  - Operating system: Windows 11
- [x] Set `{ logger: { level: LogSeverity.Debug } }` in my configuration, when applicable
- [x] Found a reliable way to reproduce the problem that indicates it's a problem with the package
I did some introspection query with Jetbrains GraphQL plugin and everything works fine.
- [x] Looked for similar issues in this repository
- [x] Checked that this isn't an issue with a Shopify API

I've been trying to set up codegen following what is describe here:
- https://shopify.dev/docs/api/shopify-app-remix/v2/guide-graphql-types
- https://github.com/Shopify/shopify-app-js/tree/main/packages/api-clients/api-codegen-preset#readme
- https://github.com/Shopify/shopify-app-js/blob/main/packages/api-clients/admin-api-client/README.md#typing-variables-and-return-objects
However nothing is working for me.

First thing, if I do not specify with the `--config` flag the path of the config file, nothing is found. Even though my file is definitely at te root of my dir and has the proper name.

Then when specifying the config file path I can see that the schemas and documents are loading but then it fails with an exit code 1 without any error logs even though I sepcified the `--debug --verbose` flags.

On a side note it feels like the syntax of projects etc... written in the doc does not totally match what is expected by `import type { CodegenConfig } from "@graphql-codegen/cli";`.

## Expected behavior

Well it should generate my types.

## Actual behavior

It fails ungracefully.

## Steps to reproduce the problem

Follow precisely what's given here:
- https://shopify.dev/docs/api/shopify-app-remix/v2/guide-graphql-types
- https://github.com/Shopify/shopify-app-js/tree/main/packages/api-clients/api-codegen-preset#readme
- https://github.com/Shopify/shopify-app-js/blob/main/packages/api-clients/admin-api-client/README.md#typing-variables-and-return-objects

## Debug logs

```
Running lifecycle hook "afterStart" scripts...
[CLI] Loading Schemas
[CLI] Loading Documents
error Command failed with exit code 1.
````

**Comment by aurelienbobenrieth** [comment]
It seems that when I only have `documents: ["!node_modules"],`the codegen works fine.

However when I include `documents: ["*.ts", "!node_modules"],`it fails.

I need to understand what is causing the failure. However withou any specific error thrown it's really hard to understand.

**Comment by paulomarg** [comment]
Hi, thanks for raising this. This is a curious one, we haven't had those issues, but maybe it's related to running it on Windows. We'll investigate it!

Just as a bit of extra context, have you tried skipping the helper functions and setting up the [full configuration](https://github.com/Shopify/shopify-app-js/tree/main/packages/api-clients/api-codegen-preset#preset) using the preset?

> On a side note it feels like the syntax of projects etc... written in the doc does not totally match what is expected by import type { CodegenConfig } from "@graphql-codegen/cli";.

Could you please provide some examples of the errors you're seeing here?

**Comment by paulomarg** [comment]
I've tried running the command on Windows, on Node 20/22, using the latest versions of all packages in a freshly created app, and I didn't get any errors.

I think the problems you're facing are related to `graphql-codegen`, more so than our preset - especially if you still see the issue without using the helpers.

My suggestion would be to see if:
- The full configuration works
- If not, if it works with all steps but using the `preset` from our package

If the error isn't related to our package, I'd suggest looking for a solution in the `graphql-codegen` repos, since there won't be much we can do.

Hope this helps!
