### ISSUE TITLE
Codegen Validation Failing with an Error /w @shopify/api-codegen-preset

### ISSUE THREAD

**Issue by xqwtsz** [Shopify/shopify-app-js#1447]
# Issue summary
I'm trying to query a [menu](https://shopify.dev/docs/api/admin-graphql/2024-07/queries/menu) that is supported in the admin api since `2024-07` but the codegen is returning this following error:

```
[1] [FAILED] GraphQL Document Validation failed with 1 errors;
[1] [FAILED]   Error 0: Cannot query field "menu" on type "QueryRoot".
```

Before opening this issue, I have:

- [x] Upgraded to the latest version of the relevant packages
  - `@shopify/*` package and version: `"@shopify/api-codegen-preset": "^1.1.1",`
  - Node version: `v20.12.2`
  - Operating system: macOS
- [ ] Set `{ logger: { level: LogSeverity.Debug } }` in my configuration, when applicable
- [x] Found a reliable way to reproduce the problem that indicates it's a problem with the package
- [x] Looked for similar issues in this repository
- [x] Checked that this isn't an issue with a Shopify API
  - If it is, please create a post in the [Shopify community forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) or report it to [Shopify Partner Support](https://help.shopify.com/en/support/partners/org-select)

Shopify Admin Graphql API v2024-07 correctly returns the expected menu from when I query from a REST Client. But I'm getting the error above from the codegen telling me that this field does not exist.

## Expected behavior

The `menu` field is correctly queried from the endpoint `https://shopify.dev/admin-graphql-direct-proxy` as the stable and current version of the api is `2024-07`

## Actual behavior

The `menu` field cannot be queried.

## Steps to reproduce the problem

1. Create a query that is using the `menu(id: "menuId")`

## Debug logs

```
[1] [FAILED] GraphQL Document Validation failed with 1 errors;
[1] [FAILED]   Error 0: Cannot query field "menu" on type "QueryRoot".
```

**Comment by lizkenyon** [comment]
I am wondering if you have a old admin.schema.json file in your project. And because you don't specify the API version it just uses that, and doesn't generate your new schema. And this is why it is working when you specify the version?

Could you try deleting your schema files if you have any and running `npm run graphql-codegen` again? 

If I am still misunderstanding your setup could you provide a sample repo that reproduces your issue?

**Comment by xqwtsz** [comment]
No no, the codegen works fine, if I add the api version the schema gets created and I no longer get the error, if I remove it again, I get the error back, so not a case of stale files, as the schema is clearly replaced correctly.

The non versioned endpoint is looking into an old version that does not have the `menu` query in it yet.

**Comment by lizkenyon** [comment]
Thank you for your .`graphqlrc`

I did some digging and my hunch currently is that the functionality hasn't changed, and our current documentation is incorrect. 
If you don't specify an API version it is defaulting to the oldest stable API version, not the latest.

**Comment by lizkenyon** [comment]
If it works for your setup to specify the API version, that is what I would currently recommend!

I am going to do a bit more research to verify if this functionality has in fact always been this way, and then update the documentation as necessary. 

Thank you for your patience!
