### ISSUE TITLE
Expose RestResources types for Typescript

### ISSUE THREAD

**Issue by wedgybo** [Shopify/shopify-app-js#1460]
## Overview/summary

Currently you can not easily get the RestResource types for the specified API version.

Importing `import type { RestResources } from '@shopify/shopify-api/rest/admin/2024-07';` gives you access to RestResource['<Resource>'] but as these are `typeof <Resource>` values you only get access to the class static information.

Using the official types would be super handy when dealing with code that is reacting to events from webhooks as we want to be sure we're using what is specified by the set API version rather than relying on writing our own types and having to manually upgrade our types when we upgrade the version.

**Comment by lizkenyon** [comment]
Thanks for flaging this!

I am going to move this to our teams backlog, to look into in the near future.

**Comment by kevpie** [comment]
Does ALL IN include webhooks? Because for now the Rest Types are helpful for those.
