### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/ts/rest/admin/2024-07' is not defined by "exports"

### ISSUE THREAD

**Issue by Zelfapp** [Shopify/shopify-app-js#1465]
# Issue summary

Before opening this issue, I have:

- [x] Upgraded to the latest version of the relevant packages
  - `@shopify/*` package and version: 11.3.0
  - Node version: v18.19.1
  - Operating system: Ubuntu 22
- [X] Set `{ logger: { level: LogSeverity.Debug } }` in my configuration, when applicable
- [X] Found a reliable way to reproduce the problem that indicates it's a problem with the package
- [X] Looked for similar issues in this repository
- [X] Checked that this isn't an issue with a Shopify API
  - If it is, please create a post in the [Shopify community forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) or report it to [Shopify Partner Support](https://help.shopify.com/en/support/partners/org-select)

## Expected behavior

```import { restResources } from '@shopify/shopify-api/dist/ts/rest/admin/2024-07'``` should import correctly.

## Actual behavior

```import { restResources } from '@shopify/shopify-api/dist/ts/rest/admin/2024-07'``` results in following error:

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/ts/rest/admin/2024-07' is not defined by "exports" in /home/me/AndroidStudioProjects/order_fulfillment/functions/node_modules/@shopify/shopify-api/package.json
    at new NodeError (node:internal/errors:405:5)
    at exportsNotFound (node:internal/modules/esm/resolve:366:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:713:9)
    at resolveExports (node:internal/modules/cjs/loader:584:36)
    at Module._findPath (node:internal/modules/cjs/loader:658:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1120:27)
    at Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/home/me/AndroidStudioProjects/order_fulfillment/functions/lib/src/lib/helperFunctions.js:53:20) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
```

## Steps to reproduce the problem

1. Try to import ```import { restResources } from '@shopify/shopify-api/dist/ts/rest/admin/2024-07'```

The docs [here](https://github.com/Shopify/shopify-app-js/blob/main/packages/apps/shopify-api/docs/guides/rest-resources.md#mounting-rest-resources) show a different path for importing the API version of restResources, but this throws typescript error if you try the way docs state. Typescript finds the REST paths at `@shopify/shopify-api/dist/ts/rest/admin/`, not `@shopify/shopify-api/rest/admin/` as the docs state.

![Image](https://github.com/user-attachments/assets/dec90af1-f944-4e93-a105-80f91cc6e4f1)

**Comment by lizkenyon** [comment]
Could you also confirm what is the typescript error you are seeing when you import like the docs say. `import { restResources } from "@shopify/shopify-api/rest/admin/2024-07";`

**Comment by Zelfapp** [comment]
I'm not getting a typescript error. My IDE is webstorm and I'm running eslint 8.23. No error are being thrown in webstorm or by eslint. The error is being thrown when I attempt to start the firebase emulator. The firebase emulator compiles typescript to js that will run in Google Cloud Functions. Starting the firebase emulator is throwing the error below. So I'm unable to deploy this. We import all sorts of libraries in our functions. This is the only one that won't compile.

![Image](https://github.com/user-attachments/assets/c25d4b60-2272-497a-877d-f1450d0dba8a)

This is at the top of our `helperFunctions.ts` file where we're trying to use `restResources`.

```javascript
import { ApiVersion, GraphqlClient, Session, Shopify, shopifyApi } from '@shopify/shopify-api'
import { v4 as uuidv4 } from 'uuid'
import { RestClient } from '@shopify/shopify-api/dist/ts/lib/clients/admin'
import { restResources } from '@shopify/shopify-api/dist/ts/rest/admin/2024-07'
```

**Comment by lizkenyon** [comment]
Sorry to clarify, you state

> The docs [here](https://github.com/Shopify/shopify-app-js/blob/main/packages/apps/shopify-api/docs/guides/rest-resources.md#mounting-rest-resources) show a different path for importing the API version of restResources, but this throws typescript error if you try the way docs state.

Could you share what is the error, in this case?

I myself haven't tried using the package in a firebase emulate, I am just trying to best understand all the issues at play 😄

**Comment by lizkenyon** [comment]
It seems like we have had [some folks with similar issues](https://github.com/Shopify/shopify-app-js/issues/856#issuecomment-2181629058) in the past and it was resolved by setting the modeResolution `bundler`.

Would you mind giving that a try?

**Comment by Zelfapp** [comment]
Changing `moduleResolution` to `Bundler` did not resolve the issue. However, in the [thread you pointed to](https://github.com/Shopify/shopify-app-js/issues/856#issuecomment-2231782827), changing 

```javascript
import { restResources } from '@shopify/shopify-api/dist/ts/rest/admin/2024-07'
```

to

```javascript
// eslint-disable-next-line @typescript-eslint/no-require-imports,@typescript-eslint/no-var-requires,@typescript-eslint/no-unsafe-assignment
const { restResources } = require(`@shopify/shopify-api/rest/admin/2024-07`)
```

As the user stated in the thread I've linked, this needs to be resolved so we can use `import`. Thanks for your help.

**Comment by hartherbert** [comment]
I am having the same issue and using require should not be the only option on this matter

**Comment by AlexRothebest** [comment]
Yep, same issue :(

**Comment by nullndr** [comment]
Can we have an update on this please? Using `require` SHOULD NOT be a soluzion

**Comment by duc-hoang-161** [comment]
I have this issue with the latest version (v12, API 2025-07) when I follow the docs to get started. After manually tracing the path to import restResources, I ended up with this.
```ts
// THIS WORKS
import { restResources } from '@shopify/shopify-api/dist/ts/rest/admin/2025-07';
// NOT THIS FROM the DOCS
import { restResources } from '@shopify/shopify-api/rest/admin/2025-07';
```

**Comment by lizkenyon** [comment]
Hi there @duc-hoang-161 

In version 4.0 we removed REST entirely, you can see this in the [changelog here](https://github.com/Shopify/shopify-app-js/blob/main/packages/apps/shopify-app-remix/CHANGELOG.md#400).

You will need to migrate from REST to GraphQL. The [changelog](https://github.com/Shopify/shopify-app-js/blob/main/packages/apps/shopify-app-remix/CHANGELOG.md#400) has some info, and there is some [extra docs here](https://shopify.dev/docs/apps/build/graphql/migrate). This is all because Shopify is [all-in on GraphQL](https://www.shopify.com/ca/partners/blog/all-in-on-graphql)

**Comment by nullndr** [comment]
@lizkenyon the problem still persist in version `4.0.1`

**Comment by lizkenyon** [comment]
Sorry @nullndr could you clarify?

Staring in version `4.0.0` we no longer provide a REST client.

You can see this in the [changelog here](https://github.com/Shopify/shopify-app-js/blob/main/packages/apps/shopify-app-remix/CHANGELOG.md#400).

You will need to migrate from REST to GraphQL. The [changelog](https://github.com/Shopify/shopify-app-js/blob/main/packages/apps/shopify-app-remix/CHANGELOG.md#400) has some info, and there is some [extra docs here](https://shopify.dev/docs/apps/build/graphql/migrate). This is all because Shopify is [all-in on GraphQL](https://www.shopify.com/ca/partners/blog/all-in-on-graphql)

**Comment by nullndr** [comment]
Sorry I was referring to the type problem mentioned here https://github.com/Shopify/shopify-app-js/issues/1465#issuecomment-2341752603

**Comment by lizkenyon** [comment]
@nullndr Could you create a new issue for this? That will help us triage and track this issue.

Could you please provide a minimal sample code reproduction of your setup so that we can best understand what the problem is.
