### ISSUE TITLE
Document what's stored for `onlineAccessInfo` in the session storages

### ISSUE THREAD

**Issue by mkevinosullivan** [Shopify/shopify-app-js#155]
# Issue summary

If developers had custom session storage that stored all fields from a session in earlier iterations of the library (e.g., prior to `v4`), using the DB adapters may cause issues since they only store the `associated_user.id` value.

## To do

Document why only `id` is stored (PII concerns) and highlight a warning to developers in the implementing custom storage guide of the risks of storing PII data and the obligations around it.

**Comment by andreydrozd** [comment]
@mkevinosullivan is `associated_user.id` the only value stored for `v5` DB adapters as well? Do the `v7` DB adapters store more information?

**Comment by mkevinosullivan** [comment]
> @mkevinosullivan is `associated_user.id` the only value stored for `v5` DB adapters as well? Do the `v7` DB adapters store more information?

The serialization/deserialization of `Session` since `v5` only includes `associated_user.id`. It has not changed in `v7` of the API library.

**Comment by owlyowl** [comment]
Did this ever get updated. I'd love to get more of an idea around `onlineAccessInfo.associated_user.collaborator` as to whether that bool implies this user is a staff member and can't approve scope increases?
