### ISSUE TITLE
[shopify-api] AWS Lambda runtime adapter

### ISSUE THREAD

**Issue by iradcn** [Shopify/shopify-app-js#1584]
## Overview

Our app's backend runs on AWS Lambda functions (using the node.js Lambda runtime).
The existing node.js adapter in this repo assumes the usage of express.js, while for AWS Lambda we're using AWS API Gateway.

We've written a runtime adapter for AWS Lambda and would love to contribute it back to this repo.

**Comment by lizkenyon** [comment]
Hi there 👋 

If you would like to contribute could you open up a PR? This PR doesn't have to be perfect, and fully documented just enough so we can get a better idea on what you have done, to decided if it makes sense to include it here. 

Looking forward to reviewing!
