### ISSUE TITLE
Webhook handling seems broken 

### ISSUE THREAD

**Issue by elnygren** [Shopify/shopify-app-js#170]
You set the `express.text({type: '*/*'}),` in https://github.com/Shopify/shopify-app-js/blob/main/packages/shopify-app-express/src/webhooks/index.ts#L24

However, won't most people have `app.use(express.json())` in their `server.ts` which already parses the body as JSON? Setting `express.text()` after it doesn't do much if the body is already parsed (and it probably is since webhooks come in with `'content-type': 'application/json'`)

This leads to the following in all webhooks:

```
[shopify-app/ERROR] Failed to process webhook: Error: No body was received when processing webhook
```

**Comment by mkevinosullivan** [comment]
In our [default app template](https://github.com/Shopify/shopify-app-template-node/blob/main/web/index.js#L20-L37), we make the call to `app.use(express.json());` _after_ we set up the webhook handling.

I guess we need to highlight this more clearly in the code and the guides.
