### ISSUE TITLE
Webhook handlers are not in correct order

### ISSUE THREAD

**Issue by gary5** [Shopify/shopify-app-js#174]
# Issue summary

- `@shopify/shopify-app-express`: v1.1.0
- Node version: v18.9.1
- Operating system:

## Expected behavior

Call multiple APP_UNINSTALLED callbacks sequentially.

## Actual behavior

The APP_UNINSTALLED callback added by shop-app-express is prior to mine.

## Steps to reproduce the problem

Add one APP_UNINSTALLED callback via processWebhooks({ webhookHandlers: ... )

## Possible solution

Await till my custom handlers added before adding default APP_UNINSTALLED handler

[shopify-app-js](https://github.com/Shopify/shopify-app-js)/[packages](https://github.com/Shopify/shopify-app-js/tree/main/packages)/[shopify-app-express](https://github.com/Shopify/shopify-app-js/tree/main/packages/shopify-app-express)/[src](https://github.com/Shopify/shopify-app-js/tree/main/packages/shopify-app-express/src)/[webhooks](https://github.com/Shopify/shopify-app-js/tree/main/packages/shopify-app-express/src/webhooks)/index.ts
![image](https://user-images.githubusercontent.com/7246502/227737373-9d2c322e-8079-42df-883c-7551f32171f0.png)

**Comment by DavidWittness** [comment]
Hey there!

This is a valid issue for versions > 2.0. A new major version was release a few weeks ago that addresses some of the async/sync issues.

Refer to the release notes here:
https://github.com/Shopify/shopify-app-js/releases/tag/%40shopify%2Fshopify-app-express%402.0.0

Details on migrating:
https://github.com/Shopify/shopify-api-js/blob/main/docs/migrating-to-v7.md#shopifywebhookaddhandlers-is-no-longer-async

I did a check with a fresh app today and it appears to be working as intended now.

<img width="1314" alt="26-52-ugmu6-jn101" src="https://user-images.githubusercontent.com/110250598/234688161-3705f33a-ada4-44a1-b1d6-85d25457a9c1.png">

Let me know if you still experience issues after upgrading.
