### ISSUE TITLE
Don't send order confirmation email using GraphQL

### ISSUE THREAD

**Issue by ChrisMadeSimple** [Shopify/shopify-app-js#1790]
## Overview

The REST api has the option of not sending the order confirmation email when creating an order with the customer ID attached. The GraphQL api does not have this option. If a draft order is completed with the customer ID attached it sends an order confirmation email. 

Additionally you cannot simply add the customer ID after completing the draft order as only the customers email can be added afterwards not the ID. So if we add the email afterwards to halt the order confirmation email, then the order doesn't get associated with the correct customer id.

**Comment by lizkenyon** [comment]
Hi there 👋 

This seems like an issue with the GraphQL API and not this library. I would recommend creating a discussion in the [developer community](https://community.shopify.dev/c/product-and-orders-apis/13). As this will go directly to the team that manages that API.
