### ISSUE TITLE
MySQLSessionStorage support for SSL/TLS: `server does not allow insecure connections, client must use SSL/TLS`

### ISSUE THREAD

**Issue by pscottchristie** [Shopify/shopify-app-js#230]
# Issue summary

I am creating a Shopify app with a MySQL Planetscale (https://planetscale.com/) database. The connection URL I have for looks like:

<pre>
DATABASE_URL='mysql://USERNAME:PASSWORD@HOST/TABLE?<b>ssl={"rejectUnauthorized":true}</b>'
</pre>

I'm passing that to the session storage constructor as it suggests in the documentation:
```
...
sessionStorage: new MySQLSessionStorage(DATABASE_URL),
...
```

But when I start my server locally, it looks like the SSL option isn't getting picked up:
```
 Error: unknown error: Code: UNAVAILABLE
  server does not allow insecure connections, client must use SSL/TLS
```
I've tried a number of different query parameters suggested in the planetscale repo to bypass this issue with no luck: 
```
?sslcert=/etc/ssl/cert.pem, ?ssl={}, sslaccept=strict,
```

Am I missing something on my side? I would expect that the ssl option would get picked up off the URL by MySQL2. I have verified that the URL is picked up correctly from my environment variables, and I have verified that I can connect using the same URL using their express.js example app: https://planetscale.com/docs/tutorials/connect-nodejs-app

- `@shopify/shopify-app-*` package and version: `"@shopify/shopify-app-express": "^2.0.0"`, `"@shopify/app": "3.45.1"`
- Node version: v20.0.0
- Operating system: macOS

## Expected behavior

Database URL with ssl query parameter should be passed to the session storage constructor,  a new session storage instance should be generated, and the app should make a connection to the DB.

## Actual behavior

Shopify app is unable to connect due to misconfigured SSL/TLS

Thanks for any help! Appreciate all the work that has gone into these tools-- much improved experience from even a year ago.

**Comment by SeanMythen** [comment]
I'm also running into a similar issue, but with the PostgreSQLSessionStorage.
I had it working 2 weeks ago. We are using a digital ocean database which also requires ssl and a certificate.
It was working before, but now it isn't, I wonder if your issue is related to mine.

**Comment by PeterChristie** [comment]
> I too am fighting the same thing, any luck yet @PeterChristie ?

Ended up writing my own SessionStorage implementation to support my DB setup. Was pretty painless, I would recommend going that route

**Comment by adamgen** [comment]
@PeterChristie, any chance you can share a snippet here?

**Comment by maruffahmed** [comment]
I'm facing the same issue using the Planetscale MySQL database. 

<img width="832" alt="Screenshot 2023-09-20 at 12 55 48 AM" src="https://github.com/Shopify/shopify-app-js/assets/39343312/1a9be44b-c70b-413a-90dd-e67418d9efd2">

<img width="839" alt="Screenshot 2023-09-20 at 12 56 07 AM" src="https://github.com/Shopify/shopify-app-js/assets/39343312/d024078f-7443-4920-9aa8-c7c168e871ce">

**Comment by brettchalupa** [comment]
I do not believe this issue should have been closed automatically. It's a legit outstanding issue that hasn't been completed. Connecting to Planetscale with `import { MySQLSessionStorage } from "@shopify/shopify-app-session-storage-mysql";` fails with the error originally reported in this issue.
