### ISSUE TITLE
Pass `X-Shopify-API-Version` and `X-Shopify-Webhook-Id` to webhook handlers

### ISSUE THREAD

**Issue by deldrid1** [Shopify/shopify-app-js#29]
## Overview
```
X-Shopify-API-Version: `2022-10`
X-Shopify-Webhook-Id: `b54557e4-bdd9-4b37-8a5f-bf7d70bcd043`
```

For runtime validation / type-sanity, it would be nice if the webhooks could be verified to be the version that you expect.  It would also be great for idempotency / logging / tracability to have the webhook ID.

**Comment by mkevinosullivan** [comment]
Added to upcoming `v6.0.1` of API librairy
