### ISSUE TITLE
DynamoDB Session Storage Handler - Resource Not Found or Key unsupported by Schema

### ISSUE THREAD

**Issue by br34th3r** [Shopify/shopify-app-js#386]
# Issue summary
Upon installing and adding the AWS DynamoDB Session Storage handler to the object with the following config:

```
sessionStorage: new DynamoDBSessionStorage({
    config: {
      region: "eu-west-2",
      credentials: {
        accessKeyId: process.env.AWS_ACCESS_KEY_ID || "",
        secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY || "",
      },
    },
  })
```

and the correct AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY values in my `.env` file, I am receiving a `Resource not Found` error when I follow the install link on a local preview and hit 'Install'. Logs below.

When I add the table in automatically, I receive a `Key provided does not match the schema` error in place of the previous error.

- `@shopify/shopify-app-*` package and version: `"@shopify/shopify-app-session-storage-dynamodb": "^1.0.4"`
- Node version: `v16.19.1`
- Operating system: `MacOS Ventura v13.4.1 (c)`

```
ResourceNotFoundException: Requested resource not found
    at de_ResourceNotFoundExceptionRes (/<My Project Folder>/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:2878:23)
    at de_GetItemCommandError (/<My Project Folder>/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:1551:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /<My Project Folder>/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at /<My Project Folder>/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:20
    at /<My Project Folder>/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at /<My Project Folder>/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
    at DynamoDBSessionStorage.loadSession (/<My Project Folder>/node_modules/@shopify/shopify-app-session-storage-dynamodb/build/cjs/dynamodb.js:34:20)
    at AuthStrategy.ensureInstalledOnShop (/<My Project Folder>/node_modules/@shopify/shopify-app-remix/build/cjs/auth/admin/authenticate.js:256:28)
    at AuthStrategy.authenticateAndGetSessionContext (/<My Project Folder>/node_modules/@shopify/shopify-app-remix/build/cjs/auth/admin/authenticate.js:117:7)
```

## Expected behavior

I believe a table should be created under the name that I provide and the session data is automatically added to it, under the correct key.

## Actual behavior

The above errors are shown in both specified problems.

## Steps to reproduce the problem

1. Create a new Remix app from the Shopify Remix template.
2. Install the AWS DynamoDB Session Storage package.
3. Use the above config to add the DynamoDB Session Storage handler to the `shopifyApp` config.
4. Make sure to fill in a valid AWS Access Key ID and Secret Key into the environment variable provider.

Happy to amend this issue if not in correct format.

**Comment by owlyowl** [comment]
You'll need to make sure the DynamoDB table with index exists.
By default the table name is `shopify_sessions` and index is `shop_index`

See source here: https://github.com/Shopify/shopify-app-js/blob/main/packages/shopify-app-session-storage-dynamodb/src/dynamodb.ts#L20

**Comment by br34th3r** [comment]
Thanks for the guidance @owlyowl, I've added in the configs separately as well to add my own index. I'm unclear as to what the 'index' is referring to. Am I to create a secondary index in DynamoDB? or do is that referring to the column name in the table itself?

**Comment by joelvh** [comment]
@br34th3r I had to look at the [tests](https://github.com/Shopify/shopify-app-js/blob/main/packages/shopify-app-session-storage-dynamodb/src/__tests__/dynamodb.test.ts#L44) to see what the table schema is.

```ts
{
  TableName: sessionTableName,
  AttributeDefinitions: [
    {AttributeName: 'id', AttributeType: 'S'},
    {AttributeName: 'shop', AttributeType: 'S'},
  ],
  KeySchema: [{AttributeName: 'id', KeyType: 'HASH'}],
  GlobalSecondaryIndexes: [
    {
      IndexName: shopIndexName,
      KeySchema: [{AttributeName: 'shop', KeyType: 'HASH'}],
      Projection: {ProjectionType: 'KEYS_ONLY'},
      ProvisionedThroughput: {
        ReadCapacityUnits: 1,
        WriteCapacityUnits: 1,
      },
    },
  ],
  ProvisionedThroughput: {ReadCapacityUnits: 1, WriteCapacityUnits: 1},
}
```

**Comment by br34th3r** [comment]
@joelvh thanks a lot for the input here! The bit I was getting tripped up on was the global secondary index, so with that schema this has solved the problem!

**Comment by joelvh** [comment]
While we're at it, this is the policy that works for me. However, for the `dynamodb:Query` action to work, this needs to be a policy attached to a user rather than an inline policy.

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Statement1",
            "Effect": "Allow",
            "Action": [
                "dynamodb:GetItem",
                "dynamodb:DeleteItem",
                "dynamodb:PutItem",
                "dynamodb:Query",
                "dynamodb:DescribeTable"
            ],
            "Resource": [
                "arn:aws:dynamodb:<region>:<account-id>:table/<table-name>"
            ]
        }
    ]
}
```

**Comment by br34th3r** [comment]
Nice setup, potentially another one to add to that PR for the docs!
