### ISSUE TITLE
Changing the auth path to outside from Remix Template

### ISSUE THREAD

**Issue by noghartt** [Shopify/shopify-app-js#390]
I would like to use an URL that I'm exposing on my backend to handle the logic that comes from `auth.$.jsx`. The solution would be turn the `auth.$.jsx` a kind of middleware that redirects the request to my endpoint.

But I would like to know if is there a way to customize the `redirect_uri` that the Remix App produces for me, instead of the `/auth` (by default), I would like to target my other endpoint o `authPathPrefix`.

**Comment by paulomarg** [comment]
I don't think you'd be able to fully skip the callback, because it sets up the token we'll use in the `admin` context after you authenticate, for instance.

That being said, if all you need is to run some custom code after the OAuth process is completed, you could try adding it to the `afterAuth` hook in your config.

In `app/shopify.server.js`, you can have:

```ts
import { redirect } from "@remix-run/node";
...
  hooks: {
    afterAuth: async ({ session }) => {
      shopify.registerWebhooks({ session });

      // Your code here, e.g.
      throw redirect('remote-url');
    },
  },
```

**Comment by noghartt** [comment]
> I don't think you'd be able to fully skip the callback, because it sets up the token we'll use in the `admin` context after you authenticate, for instance.
> 
> That being said, if all you need is to run some custom code after the OAuth process is completed, you could try adding it to the `afterAuth` hook in your config.
> 
> In `app/shopify.server.js`, you can have:
> 
> ```ts
> import { redirect } from "@remix-run/node";
> ...
>   hooks: {
>     afterAuth: async ({ session }) => {
>       shopify.registerWebhooks({ session });
> 
>       // Your code here, e.g.
>       throw redirect('remote-url');
>     },
>   },
> ```

Oh, thank you!

In case, I did something different that seems to work for me in this scenario. I target the `/auth` flow directly from the App URL and handling this on my side, and handle the OAuth logic using the `@shopify/shopify-api`.

But, for this scenario, I have a little doubt. Do you know if it's possible to use the Remix template only for the _"front-end stuffs"_ of my embedded app? Or what do you suggest in this scenario where I need to have the OAuth/session logic inside another domain (from App URL).

Other doubt: could you refer to me where in the Remix code is the logic to set the `admin` context? I'm having some doubts on it.
