### ISSUE TITLE
Enable a way to specify a port when running pnpm dev

### ISSUE THREAD

**Issue by TzuTech** [Shopify/shopify-app-js#398]
## Overview/summary

Facilitate development against OAuth platforms, introduce a feature to the `pnpm dev` command that allows developers to specify a custom port number. This is essential as many OAuth platforms require the port number to be set in their redirect URI for development purposes, ensuring seamless integration and testing.

Currently developing a Shopify app with @shopify/shopify-app-remix. If there is a way make it clear in the docs. There is no mention of a port flag anywhere.

**Comment by paulomarg** [comment]
I think this is more of a CLI issue, but you should be able to do this using the `port` setting in your `shopify.web.toml` file.

Here is [the documentation for that](https://shopify.dev/docs/apps/tools/cli/structure#web-components:~:text=Specifies%20which%20port%20to%20use%20to%20run%20your%20frontend%20or%20backend%20process.%20If%20you%20don%27t%20specify%20a%20port%2C%20then%20a%20random%20one%20is%20assigned%20when%20you%20run%20dev).

Could you please try that to see if it fixes your issue?
