### ISSUE TITLE
[Enhancement] Upgrade `@shopify/shopify-app-session-storage-prisma` to Prisma v5

### ISSUE THREAD

**Issue by blanklob** [Shopify/shopify-app-js#400]
## Overview/summary

-- Resources -- 

https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-5

**Comment by byrichardpowell** [comment]
Hey @blanklob Thanks for opening this issue.

The timing of the Prisma V5 release was funny.  Just as we went live with the prisma package

We'll get to, but to set expectations it's somewhere down the list.

**Comment by blazestudios23** [comment]
Any update on when this will be bumped up? Will it even break anything to move it up to 5?

**Comment by boxedcode** [comment]
Any update from the Shopify team on this enhancement?

**Comment by Rafi993** [comment]
+1

**Comment by yuvrajharod** [comment]
hey @byrichardpowell , really need this one as it brings major feature updates, I tried updating myself but it's dependent on this package which make this really important...

**Comment by Alex-Levacher** [comment]
Hey Shopify team 👋🏻 Is there any reason to not upgrade the Prisma version ? Thank you 😊

**Comment by paulomarg** [comment]
Sorry for the delay folks, we're looking into it as per #589!

**Comment by blanklob** [comment]
No upgrade guide right I just update remix app package and prisma?

**Comment by paulomarg** [comment]
We're planning on releasing soon!
