### ISSUE TITLE
validateAuthenticatedSession performance improvment

### ISSUE THREAD

**Issue by idangozlan** [Shopify/shopify-app-js#403]
As of today, the `shopify-app-express` lib middleware `validateAuthenticatedSession` calls `hasValidAccessToken`, which makes a super slow GQL test request that sometimes can take up to a second. Since this middleware should be used on every API call, I suggest either creating a designated test query that can run much faster or finding another solution to verify that the client is ready / let the developer decide whether to verify across this test query.
The current state requires us to fork this middleware and create a custom one without this GQL test query, to improve the user experience.

I spotted around 1s duration for this gql call to run from GCP servers, which is obviously unacceptable.

Reference:
https://github.com/Shopify/shopify-app-js/blob/main/packages/shopify-app-express/src/middlewares/has-valid-access-token.ts

**Comment by thosakwe** [comment]
Did you ever find a solution for this? In my testing, `validateAuthenticatedSession` can easily add upwards of 500ms to request times. This makes it pretty hard to maintain an LCP below 2.5s.

If I figure anything out, I'll comment here. Right now, I'm considering just copying `validateAuthenticatedSession` and removing the test GraphQL query.
