### ISSUE TITLE
session-storage-prisma Custom Model Name

### ISSUE THREAD

**Issue by TheRealFlyingCoder** [Shopify/shopify-app-js#418]
Pretty simple, I'd like to be able to pass an option for a different model name to the helper.

`const storage = new PrismaSessionStorage(prisma, 'shopifySession');`

Or alternatively just let the user pass through the delegate for their specific session model:

`const storage = new PrismaSessionStorage(prisma.shopifySession);`

The first is a non-breaking change by adding the optional `customModel?: keyof typeof T`

The second would be a breaking change but realistically be better DX

**Comment by byrichardpowell** [comment]
Please see comment here: https://github.com/Shopify/shopify-app-js/pull/419#issuecomment-1701586502
