### ISSUE TITLE
Cannot combine billing models in a pricing plan

### ISSUE THREAD

**Issue by bhr** [Shopify/shopify-app-js#434]
# Issue summary

I'd like to combine a subscription with a usage model in one pricing plan as shown here in [the GraphQL howto](https://shopify.dev/docs/apps/billing/subscriptions/recurring-charges-based-on-usage#step-2-combine-billing-models-in-a-pricing-plan).

The combined plan contains two line items in the GraphQL example. The `BillingConfig` `@shopify/shopify-api` doesn't seem to allow for that?
- `@shopify/shopify-app-*` package and version: "@shopify/shopify-api": "^7.5.1",
- Node version: v16

## Expected behavior

Ability to create a plan that has multiple billing models

## Actual behavior

Not able to do that with the current API

**Comment by smartraysam** [comment]
I use graphql mutation query to combine a fixed and usage charge.
But hwn I redirect. I cannot proceed because the approval button was disable..

Do you encounter this issue..
