### ISSUE TITLE
Allow Typescript Typing for GraphQL calls.

### ISSUE THREAD

**Issue by dan-gamble** [Shopify/shopify-app-js#436]
With the `shopify-api-js` you can type the return value of a GraphQL query like so:
```typescript
// If using TypeScript, you can type the response body
interface MyResponseBodyType {
  data: {
    //...
  };
}

const response = await client.query<MyResponseBodyType>({
  /* ... */
});

// response.body will be of type MyResponseBodyType
console.log(response.body.data);
```

[Using the proxy in the remix app](https://github.com/Shopify/shopify-app-js/blob/main/packages/shopify-app-remix/src/server/clients/admin/graphql.ts#L39) doesn't allow the ability to do that.

At the moment I'm having to use a very janky (and I'm sure awfully done) method to proxy everything through to allow for this:
```typescript
export async function makeGraphQLRequest<T, V extends Record<string, unknown>> (
  graphql: GraphqlQueryFunction,
  document: string | DocumentNode | TypedDocumentNode<T, V>,
  variables: V,
): Promise<{ data: T }> {
  const response = await graphql(
    typeof document === 'string' ? document : print(document),
    {
      variables,
    }
  )

  return await response.json() as {
    data: T;
  }
}
```

Would it be possible to allow for the type to be passed to the `admin.graphql` call?

**Comment by paulomarg** [comment]
Hi, thanks for pointing this out, this is a great callout. We'll look into adding back a way to type the response in that call!

**Comment by patrickDouglas** [comment]
I'd love to help out with this if I can.  I'd love to add this to my app as well.

**Comment by byrichardpowell** [comment]
Hey everyone 👋 

We looked into this and wondered if there is an easier way:

```
const {admin} = authenticate.admin(request)

const response = admin.graphql(MY_QUERY)
const responseJson: {data: {productCreate: {product: string}}} = await response.json();
```

We think this might be viable since `response.json()` returns `any`.

How does that work for you two?

**Comment by alexandrosk** [comment]
@paulomarg 
Thanks for the update! 
Can we follow this package somewhere and see when it will be deployed? @shopify/api-codegen-preset

**Comment by xaviergmail** [comment]
Any news? I'd also like to know how to achieve this. New to the Shopify ecosystem, not sure where to look or keep an eye out for said new clients.

**Comment by paulomarg** [comment]
Hey! That endpoint is POST-only - it's set up in a way that will respond to schema introspection requests, like the ones made by codegen / graphqlrc. It should be responding to POST requests now.
