### ISSUE TITLE
Unrecognized delivery method 'undefined'

### ISSUE THREAD

**Issue by jeff0723** [Shopify/shopify-app-js#440]
# Issue summary

I am using cli generated version app, however, past couple months I don't have this issue when I install it. 

Now I have it.

Whenever I install the app, I will receive this error:

`Unrecognized delivery method 'undefined'`

-->

- `@shopify/shopify-app-*` package and version:^1.0.0
- Node version: 18
- Operating system:MAC

```
// Paste any relevant logs here
```
<img width="1269" alt="Screenshot 2023-09-11 at 16 34 30" src="https://github.com/Shopify/shopify-app-js/assets/38219877/6193894e-470c-4c46-a0f5-996f9c552fd6">

## Expected behavior

Should install successfully

## Actual behavior

Can't install

## Steps to reproduce the problem

1. Install this public app: https://apps.shopify.com/notification-app-1

**Comment by paulomarg** [comment]
I believe this error is related to your webhooks configuration - do you have any webhooks that are missing a `deliveryMethod` value?

It might also make it easier to spot what's going wrong if you turn on HTTP request logging. To do that, you can add this to your config:

```ts
api: {
  logger: {
    level: LogSeverity.Debug,
    httpRequests: true,
  }
}
```

that should show you exactly what request the library is sending when registering webhooks, and it should help figure out what is going wrong.

Hope this helps!
