### ISSUE TITLE
window.shopify.resourcePicker ignores showVariants option

### ISSUE THREAD

**Issue by redpandatronicsuk** [Shopify/shopify-app-js#454]
I'm migrating a Shopify app to use the new Remix framework. In the old app I used

```jsx
<ResourcePicker
        resourceType="Product"
        showVariants={false}
        selectMultiple={false}
        …
      /> 
```

When using

```js
window.shopify.resourcePicker({
        type: "product",
        action: "select",
        multiple: true,
        showVariants: false
})
```

The `showVariants` option is ignored.

How do you hide variants using `window.shopify.resourcePicker`?

**Comment by henrytao-me** [comment]
It's part of `filter` now. See https://shopify.dev/docs/api/app-bridge-library/reference/resource-picker

```ts
window.shopify.resourcePicker({
        type: "product",
        action: "select",
        multiple: true,
        fitler: {
               variants: false
        }
})
```

**Comment by mur-wtag** [comment]
hey @henrytao-me you saved my day man! thanks a lot!

**Comment by huykon** [comment]
@henrytao-me do you know the way to add picker type product tags?
