### ISSUE TITLE
Redirect to billing confiramtion - express

### ISSUE THREAD

**Issue by tamir-boaideas** [Shopify/shopify-app-js#466]
# Issue summary

As I found out there isn't a billing model that combines both fixed price and usage in the package yet, I created one myself, and after setting up a billing confirmation URL, I would like to redirect the merchant to it.

The res.redirect command fails with the error "refuse to connect".

I tried using [redirectOutOfApp](https://github.com/Shopify/shopify-app-js/blob/main/packages/shopify-app-express/docs/reference/redirectOutOfApp.md#shopifyredirectoutofapp) and it seems to be doing the right thing (the URL changes to existframe with the correct URL), but it does not redirect to the confirmation page either.
It doesn't work even if the redirectURI is to google.com (you can see in the network tab on dev tools that the request is cancelled)

When I return the confirmation URL to the frontend via API call and then use the useNavigate hook, it works, but I don't want my frontend to handle it. 

Is there another way to do this? Is there something I did wrong?

- `@shopify/shopify-app-*` package and version: 2.2.4
- Node version: 20.8
- Operating system: MacOS

**Comment by smartraysam** [comment]
Were  you able to resolve this issue.
I use graphql mutation query to combine a fixed and usage charge. 
But hwn I redirect. I cannot proceed because the approval button was disable..

Do you encounter this issue..

**Comment by smartraysam** [comment]
Thanks . Got the issue resolved
