### ISSUE TITLE
[shopify-app-remix] get authenticated user details

### ISSUE THREAD

**Issue by boxedcode** [Shopify/shopify-app-js#472]
## Overview

Hi.

Currently, when authenticating a Shopify Remix app with `authenticate.admin(request)` with `useOnlineTokens` set to `true`, the session only contains the authenticated users id. I've had a look at the Admin API reference for `graphql` and `rest` and there doesn't appear to be a request to fetch the users details.

For some context, I have an app where I want to display a timeline of events for actions performed within the app, e.g.

`Settings last updated by Joe on Oct 13, 2023 at 14:23`

where Joe is a user who authenticated with my app.

How would I obtain Joe's name?

Thank you.

**Comment by joelvh** [comment]
@boxedcode there should be an OAuth redirect to install the app (offline token) and then redirect again to authenticate the user (online token). The result should include both the offline and online token, with the user info under `associated_user` (something like [this mocked response](https://github.com/Shopify/shopify-app-js/blob/ab35d95e6a09d16973eae70562d9562c20490738/packages/shopify-app-remix/src/server/authenticate/admin/__tests__/auth-callback-path.test.ts#L343)).

What session storage are you using?

**Comment by boxedcode** [comment]
@joelvh Thanks for your response, appreciate it.

I'm using `prisma` for session storage with `mysql` as the storage engine. I'll go through the flow again to see if I can spot the user data in the session response

**Comment by boxedcode** [comment]
I just went through the flow again, and the only data that appears to be populated for the session is the users id,

```
onlineAccessInfo: { associated_user: { id: 9854713913 } }
```

The default mysql schema for the shopify-app-remix template is

```
CREATE TABLE "Session" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "shop" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "isOnline" BOOLEAN NOT NULL DEFAULT false,
    "scope" TEXT,
    "expires" DATETIME,
    "accessToken" TEXT NOT NULL,
    "userId" BIGINT
);
```

and the documentation here reinforces the fact that only the `id` is available for the associated user. https://shopify.dev/docs/api/shopify-app-remix/v1/authenticate/admin#session-using-online-sessions

**Comment by nullndr** [comment]
Any news on this? I would like to retrieve the user locale to translate my app according. I can see from the types I should be able to get it via the `session.toObject().onlineAccessInfo` object but it is always `undefined`.
