### ISSUE TITLE
[shopify-app-remix] Billing request with custom returnUrl not working as expected

### ISSUE THREAD

**Issue by boxedcode** [Shopify/shopify-app-js#476]
Hi there. 

I'm trying to use the `billing` helper from `shopify-app-remix` to charge for a subscription using a **custom return URL**. 

The documentation at this link seems incomplete as it suggests you can provide a relative URL, but in practice, it errors if you don't provide an absolute URL: https://shopify.dev/docs/api/shopify-app-remix/v1/authenticate/admin#require-using-a-plan-selection-page 

When you do provide an absolute URL, you lose the session after approving the charge and the user is taken through the authorisation flow again and the `charge_id` provided in the original redirect request is lost. 

I have a few questions on this:

- Is the custom return URL supposed to include some additional query params in order to restore the previous session that existed?
- Is there an undocumented way that the custom return URL scenario needs to be handled?

**This is how I first implemented the billing request, initially with a relative URL which errored and then with an absolute URL. I didn't originally append the `shop` query argument, so I added that on to see if it would make a difference, but it didn't.**

```
  const url = new URL(
    `/app/plan/buy/complete?shop=${session.shop}`,
    process.env.SHOPIFY_APP_URL
  );

await billing.request({
    plan: plan.name,
    isTest: process.env.NODE_ENV !== "production",
    returnUrl: url.href,
  });
```

**Digging into the options available for `billing.request`**, 

```
export type BillingRequestParams = {
    session: Session;
    plan: string;
    isTest?: boolean;
    returnUrl?: string;
    returnObject?: boolean;
} 
```

**I noticed that it accepts a `session` option, so I proceeded to add that.**

```
await billing.request({
    session: session,
    plan: plan.name,
    isTest: process.env.NODE_ENV !== "production",
    returnUrl: url.href,
  });
```

However, that didn't make a difference, and on return to the app after approving the charge, I was redirected to `/auth/login` to go through authorisation again.

**I then decided to try the billing request without providing a custom return URL:**

```
await billing.request({
    plan: plan.name,
    isTest: process.env.NODE_ENV !== "production",
  });
```

After approving the charge, I was taken back to the index page of the app with a `charge_id` query parameter. e.g. `/app?charge_id=24449613881`

I can of course handle this if that is only way it'll work, but I want to make sure I'm not missing something obvious with the implementation that uses a custom return URL for billing approval.

Thanks

**Comment by lizkenyon** [comment]
Hi there 👋 

Thank you for writing up this detailed feedback. At this time we would recommend using your workaround of not specifying the custom URL. 

Though we do understand that this is not ideal, so we will work towards resolving this, and allowing custom URLs.

**Comment by lanesky** [comment]
I believe the issue stems from the tunneling URL being different from the Shopify domain. As a result, the session needs to be reinitiated if the `returnURL` includes `process.env.SHOPIFY_APP_URL` as one part of it.

There's a straightforward workaround -  use the `launchUrl` from querying `currentAppInstallation` .

For more information, you can refer to the Shopify documentation:

https://shopify.dev/docs/api/admin-graphql/2023-07/objects/appinstallation

Below is a sample code snippet:

```js
export async function retreiveApplicationLaunchUrl(graphql) {
  let response = await graphql(
    `
      query {
        currentAppInstallation {
          launchUrl
        }
      }
    `
  );
  const {
    data: {
      currentAppInstallation: { launchUrl }
    }
  } = await response.json();
  return launchUrl;
}
```

Finally, you can set the `returnUrl` to something like `${launchUrl}/app/plan/buy/complete?shop=${session.shop}`.

```

**Comment by kabudu** [comment]
@lanesky Thanks, makes sense. I'll give it a try.

**Comment by boxedcode** [comment]
@lanesky Thanks, it does make sense. I'll give it a try.
