### ISSUE TITLE
[shopify-app-remix] Inconsistency in REST resources namespacing

### ISSUE THREAD

**Issue by boxedcode** [Shopify/shopify-app-js#490]
# Issue summary

There is an inconsistency in the namespacing of `admin.rest` resources between authenticating an `admin` request and authenticating a `webhook` request. I don't know if there is a particular reason for this difference, or if it is a bug.

- `@shopify/shopify-app-remix:2.1.0`
- Node version: v19.1.0
- Operating system: MacOS Sonoma 14.1.1 (23B81)

## Expected behavior

Authenticating with either of the following should ensure that the `rest` resources are always available from the same namespace.

```
const { admin } = await authenticate.admin(request);
const { admin } = await authenticate.webhook(request);
```

Using the `rest` resource `RecurringApplicationCharge`, my expectation is that it would always be available at:

`admin.rest.RecurringApplicationCharge`

## Actual behavior

**Admin request**

```
const { admin } = await authenticate.admin(request);

admin.rest.resources.RecurringApplicationCharge
```

**Webhook request**

```
const { admin } = await authenticate.webhook(request);

admin.rest.RecurringApplicationCharge
```

This requires logic such as the following to handle both contexts within a single block of code

```
const recurringApplicationChargeObject = rest.RecurringApplicationCharge || rest.resources.RecurringApplicationCharge;
```

## Steps to reproduce the problem

1. Authenticate an `admin` request and fetch a particular rest resource using `admin.rest.resources.RecurringApplicationCharge.find(...)`
1. Authenticate a `webhook` request and fetch a particular rest resource using `admin.rest.resources.RecurringApplicationCharge.find(...)`
1. In the case of the `webhook`, an error will be thrown as you're calling a property `RecurringApplicationCharge` of an object that is `undefined`

**Comment by paulomarg** [comment]
Hey, thank you for reporting this! This was actually a mistake we made when we first released this package, where the admin context returned by the webhook call was a little different.

Luckily, we've already fixed it :)

If you enable the `v3_webhookAdminContext` future flag in your `/app/shopify.server` file ([example](https://github.com/Shopify/shopify-app-template-remix/blob/main/app/shopify.server.ts#L34)), calls to `authenticate.webhook` will return the exact same context object we return from other places.

Please let me know if you still run into other issues after enabling that.
