### ISSUE TITLE
Support for API 2024-01 / Webhook subtopics

### ISSUE THREAD

**Issue by nboliver-ventureweb** [Shopify/shopify-app-js#565]
API 2024-01 has [required webhook subtopics](https://shopify.dev/docs/apps/webhooks/sub-topics), but there doesn't appear to be a way to register them with the Remix app template / `shopifyApp` function. Will support be added soon?

**Comment by lizkenyon** [comment]
Hi there 👋 

A new version of this package should be released now, [shopify-app-express](https://www.npmjs.com/package/@shopify/shopify-app-express) (4.0.0) and [shopify-app-remix](https://www.npmjs.com/package/@shopify/shopify-app-remix) (2.3.0)

**Comment by lizkenyon** [comment]
Hi there 👋 

Sorry, my mistake. No, we have not added support for subTopics yet. Thank you for flagging. The team will get some eyes on this.

**Comment by BARK-CMORENO** [comment]
Hi @lizkenyon is there a timeline for this?

**Comment by BARK-CMORENO** [comment]
> Hi @BARK-CMORENO Thanks for the flag. This is a priority for us. Someone from the team will be taking a look at that in the coming weeks.

Thank you. Looking forward for the release of this.

**Comment by nboliver-ventureweb** [comment]
@BARK-CMORENO As an interim measure while we wait for subtopic support, I added metaobject webhooks to my dev app via GraphiQL using the newest version of the CLI. Seems to be working pretty well. There's an example of the subscription create mutation here: https://shopify.dev/docs/api/admin-graphql/2024-01/mutations/webhooksubscriptioncreate#examples-Create_a_METAOBJECTS_CREATE_webhook_subscription_for_lookbook_metaobjects
