### ISSUE TITLE
How can I use GQL fragments?

### ISSUE THREAD

**Issue by MoSattler** [Shopify/shopify-app-js#585]
I would like to reuse fragments across multiple GQL requests. Whats the recommend way to go about this?
I tried this, but the codegen mentioned [here](https://shopify.dev/docs/api/shopify-app-remix/v2/guide-graphql-types) is giving me an error ("unknown fragment").

![Screenshot 2024-01-18 at 10 59 37](https://github.com/Shopify/shopify-app-js/assets/64152453/ff4f06db-9ebf-434e-b03b-bba895f11435)

![Screenshot 2024-01-18 at 11 06 59](https://github.com/Shopify/shopify-app-js/assets/64152453/f3ba3a59-84a1-4db0-bd46-abe5ab7aeb01)

**Comment by DenisRupp** [comment]
Hey, any updates on this? @MoSattler Can you share discussion on [https://community.shopify.com](https://community.shopify.com/c/shopify-cli-and-tools/bd-p/tools) ?

**Comment by kfiroo** [comment]
For anyone still looking for a solution, I got this to work by adding the fragments content to query itself.
Something like this:
```ts
const productFieldsFragment = `
  #graphql
  fragment ProductFields on Product {
    id
    title
    handle
    description
  }
`

const response = await admin.graphql(`
    #graphql

    ${productFieldsFragment}
    
    query getProduct($id: ID!) {
      product(id: $id) {
        ...ProductFields
      }
    }
  `,
  {
    variables: {
      id: 'gid://shopify/Product/1234567890',
    },
  },
)
```
