### ISSUE TITLE
Auth 500 when Add Shopify App Bridge In Build A Shopify App With Node And React Tutorial

### ISSUE THREAD

**Issue by qjszgithub** [Shopify/shopify-app-js#595]
## Overview

When go through the sections code updates and attempt to re-authenticate using the URL provided (with my app info inserted)[ https://YOUR_NGROK_ADDRESS.io/auth?shop=YOUR_SHOPIFY_STORE.myshopify.com](https://your_ngrok_address.io/auth?shop=YOUR_SHOPIFY_STORE.myshopify.com) the webpage is displaying an Internal Server Error -

Failed to load resource: the server responded with a status of 500 ().

![image](https://github.com/Shopify/shopify-app-js/assets/30100341/8a66d9f5-b236-46be-8333-3c765fcabd4d)

![image](https://github.com/Shopify/shopify-app-js/assets/30100341/64b7d1ac-d358-46b4-8cb3-86be9ad1c8d6)

**Comment by paulomarg** [comment]
Hi, sorry to hear you're having issues! Based on the error message, it sounds like your server is having issues reaching `<shop>.myshopify.com`, so the first step would to be ensure that the server can make network requests to that address.

Unfortunately, there won't be much we can do from this package if there is a network issue, but let us know if you run into any issues with the package itself and we'll fix it.
