### ISSUE TITLE
Upstash session store

### ISSUE THREAD

**Issue by gil--** [Shopify/shopify-app-js#60]
## Overview

I've open sourced an initial basic implementation of [Upstash](https://upstash.com) as a session store. Upstash is essentially a hosted Redis: https://github.com/Checkout-Blocks/Shopify-App-Examples/blob/main/checkout-to-draft-with-upstash-sessions/web/api-lib/session-storage.js

Are you open to accepting 3rd party session storage implementations?

## Type

- [X] New feature

## Motivation

Simple session storage using Upstash for small apps

**Comment by paulomarg** [comment]
Hi, and thanks for the proposal! We're definitely open to community contributions, but we're still defining whether we'll prefer community-created packages that we can recommend here, or community additions to this repo. I'll sync up with the team and get back to you!

As for Upstash specifically, is there a particular reason why our "regular" Redis client doesn't work for you? Is there something we could improve in the package to cover the Upstash case as well?
