### ISSUE TITLE
Storefront GraphQL types do not provide validation despite `storefront.generated.d.ts` file being generated

### ISSUE THREAD

**Issue by kyrylo-soulandwolf** [Shopify/shopify-app-js#694]
# Issue summary

  - `@shopify/shopify-app-remix`: 2.6.1
  `@shopify/shopify-api`: 9.5.0
  `@shopify/app`: 3.57.0
  `@shopify/cli`: 3.57.0
  `@shopify/api-codegen-preset`: 0.0.5
  - Node version: 20.11.0
  - Operating system: Ubuntu 22.04

There seems to be a problem with Storefront types on the freshly created Remix app. Generating types with the provided npm script doesn't seem to add any typings/validation despite `storefront.types.d.ts` file getting generated. The types for the Admin queries/mutations work as expected.

## Expected behavior

Unless my understanding is incorrect, I expect to get the autocomplete functionality and typescript validation for the return value as well, as any query variables when the types were generated with `npm run graphql-codegen`.

## Actual behavior

The `storefront.generated.d.ts` file gets generated including correct types based on query/mutation strings, however, it is not used by the `storefront.graphql` function making all the returns of type `any` and not validating `variables` object.

## Steps to reproduce the problem

1. Create a clean Remix app (using typescript).
2. Update `@shopify/api-codegen-preset` module to the latest version which is `0.0.5` at the time of writing. 
3. Change `apiType` in the `.graphqlrc.ts` file to `ApiType.Storefront`. You must remove the `#graphql` string that ships with the Remix app template in the `app._index.tsx` file. While it is possible to generate both Admin and Storefront graphql types, we'll just use storefront for the simplicity of the repro.
4. Create proxy route file `proxy.tsx`:
  ```javascript
  import { json, type LoaderFunctionArgs } from "@remix-run/node";
  import { authenticate } from "~/shopify.server";
  
  export async function loader({ request }: LoaderFunctionArgs) {
    const { storefront } = await authenticate.public.appProxy(request);
  
    const res = await storefront?.graphql(
      `#graphql
        query getShop {
          shop {
            id
            name
          }
        }
      `,
    );
    // `data` is of type FetchResponseBody<any>
    const data = await res?.json();
  
    return json({ data });
  }
  ```
5. Run `npm run graphql-codegen`

## Debug logs
Generated `storefront.generated.d.ts` for reference:
  ```typescript
  /* eslint-disable eslint-comments/disable-enable-pair */
  /* eslint-disable eslint-comments/no-unlimited-disable */
  /* eslint-disable */
  import * as StorefrontTypes from './storefront.types.d.ts';
  
  export type GetShopQueryVariables = StorefrontTypes.Exact<{ [key: string]: never; }>;
  
  
  export type GetShopQuery = { shop: Pick<StorefrontTypes.Shop, 'id' | 'name'> };
  
  interface GeneratedQueryTypes {
    "#graphql\n      query getShop {\n        shop {\n          id\n          name\n        }\n      }\n    ": {return: GetShopQuery, variables: GetShopQueryVariables},
  }
  
  interface GeneratedMutationTypes {
  }
  declare module '@shopify/storefront-api-client' {
    type InputMaybe<T> = StorefrontTypes.InputMaybe<T>;
    interface StorefrontQueries extends GeneratedQueryTypes {}
    interface StorefrontMutations extends GeneratedMutationTypes {}
  }
  ```

**Comment by kyrylo-soulandwolf** [comment]
Hey @paulomarg, thanks for this suggestion
I've just tried this, but adding `@shopify/storefront-api-client` explicitly doesn't change anything.

Also, I don't have `@shopify/admin-api-client` in the `package.json` either, but Admin types seem to work as expected.

**Comment by paulomarg** [comment]
I was digging some more into this, and it happened because `@shopify/shopify-app-remix` had a different version of `@shopify/storefront-api-client`, which made it install two versions of it. Since now all packages are released from the same repo, updating both packages will fix this.

I'm going to close this issue since there is no action to take, but please let us know if it still fails after the next release (coming soon!).
