### ISSUE TITLE
[shopify-app-remix] Authenticate Webhook returns undefined Admin object

### ISSUE THREAD

**Issue by JanKrueckemeier** [Shopify/shopify-app-js#708]
# Issue summary

  - @shopify/shopify-app-remix@2.7.0
  @shopify/shopify-app-session-storage-prisma@4.0.2
  - Node version: v20.10.0
  - Operating system: Windows 11

```
//webhooks.jsx
import { authenticate } from "../shopify.server";

export const action = async ({ request }) => {
  const { topic, shop, billing, session, admin, payload } = await authenticate.webhook(request);
  console.log('Webhook received for shop', shop, 'with topic', topic, 'and admin', admin);
};
```

```
//shopify.server.js
import {
  AppDistribution,
  DeliveryMethod,
  shopifyApp,
  LATEST_API_VERSION,
  BillingInterval,
} from "@shopify/shopify-app-remix/server";

const shopify = shopifyApp({
  apiKey: process.env.SHOPIFY_API_KEY,
  apiSecretKey: process.env.SHOPIFY_API_SECRET || "",
  apiVersion: LATEST_API_VERSION,
  scopes: process.env.SCOPES?.split(","),
  appUrl: process.env.SHOPIFY_APP_URL || "",
  authPathPrefix: "/auth",
  sessionStorage: new PrismaSessionStorage(prisma),
  distribution: AppDistribution.AppStore,
  restResources,
  webhooks: {
    APP_UNINSTALLED: {
      deliveryMethod: DeliveryMethod.Http,
      callbackUrl: "/webhooks",
    },
    APP_SUBSCRIPTIONS_UPDATE: {
      deliveryMethod: DeliveryMethod.Http,
      callbackUrl: "/webhooks",
    },
    ORDERS_CREATE: {
      deliveryMethod: DeliveryMethod.Http,
      callbackUrl: "/webhooks",
    },
  },
  hooks: {
    afterAuth: async ({ session }) => {
      ...
      await shopify.registerWebhooks({ session });
      ...
    }
  },
  future: {
    v3_webhookAdminContext: true,
    v3_authenticatePublic: true,
    unstable_newEmbeddedAuthStrategy: true,
    v3_lineItemBilling: true,
  },
  ...(process.env.SHOP_CUSTOM_DOMAIN
    ? { customShopDomains: [process.env.SHOP_CUSTOM_DOMAIN] }
    : {}),
});
```

## Expected behavior

After an ORDERS_CREATE webhook request gets sent by shopify the await authenticate.webhook(request) function should return a valid admin object for the store.

## Actual behavior

The authenticate.webhook(request) function returns an undefined admin object for specific stores during a random time window. This means that different stores that have the app installed have random periods where the function returns an undefined admin object. After x days it works again for y days for shop z.
I only encounter this problem for the ORDERS_CREATE webhook.

## Steps to reproduce the problem

1. Register ORDERS_CREATE webhook within app
2. Multiple Stores install App & Order gets created
3. For some stores the authenticate.webhook(request) function returns an undefined admin object

## Debug logs

>> Webhook received for shop XX.myshopify.com with topic ORDERS_CREATE and admin undefined

**Comment by mohamedhaddi** [comment]
Hey @JanKrueckemeier, would you please let me know did you solve this issue?
