### ISSUE TITLE
DynamoDB session store

### ISSUE THREAD

**Issue by lukeclifton** [Shopify/shopify-app-js#72]
We are planning to use DynamoDB for our application. Just creating this issue here in case others also have a need for it?

We could contribute a Dynamo DB session store package if you decide to accept community packages.

**Comment by GabeL7r** [comment]
@lukeclifton we are using DynamoDB and developing a Dynamo DB session store package as well. Have you created the package yet? We've almost completed our implementation but running into a some minor issues.

**Comment by lukeclifton** [comment]
Hi @GabeL7r. We have not started yet. What issues are you running into? Maybe we can help?

cc @guptalav

**Comment by sisrio** [comment]
Dynamo DB session will be a huge plus for us too. Please release the package asap. Looking forward to it.

**Comment by zirkelc** [comment]
I submitted PR https://github.com/Shopify/shopify-app-js/pull/167 

Let me know what you guys think!
