### ISSUE TITLE
Support drizzle-orm v0.30 for @shopify/shopify-app-session-storage-drizzle

### ISSUE THREAD

**Issue by simplystuart** [Shopify/shopify-app-js#730]
## Overview/summary

[`drizzle-orm` 0.30.0](https://github.com/drizzle-team/drizzle-orm/releases/tag/0.30.0) updated the handling of timestamps for Postgres. Handling of timestamps for Postres in previous versions of `drizzle-orm` was buggy, but v0.30 was released as a minor patch as a warning that the release could introduce breaking changes. From the release:
> We've made this change as a minor release, just as a warning, that:

> If you were using timestamps and were waiting for a specific response, the behavior will now be changed.
When mapping to the driver, we will always use .toISOString for both timestamps with timezone and without timezone.

> If you were using the postgres.js driver outside of Drizzle, all postgres.js clients passed to Drizzle will have mutated behavior for dates. All dates will be strings in the response.

---

Additionally, if you are using the latest `drizzle-orm` with `@shopify/shopify-app-session-storage-drizzle@1.0.0` you get the following error from `npm`:

```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: my-library@undefined
npm ERR! Found: drizzle-orm@0.30.6
npm ERR! node_modules/drizzle-orm
npm ERR!   drizzle-orm@"^0.30.5" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer drizzle-orm@"^0.29.3" from @shopify/shopify-app-session-storage-drizzle@1.0.0
npm ERR! node_modules/@shopify/shopify-app-session-storage-drizzle
npm ERR!   @shopify/shopify-app-session-storage-drizzle@"^1.0.0" from the root project
```

I see this as both a bug and an enhancement, but the workaround is to use `npm -f`.

**Comment by paulomarg** [comment]
Hey, thanks for bringing this up! We only have one date in the adapter, for the session expiry. We'd need to test how it behaves to see if it would break for online sessions (though our tests should cover it), but I'm surprised to see the dependency fails - `^0.29.3` should be compatible with `^0.30.5` - they should work for anything under `1.0.0`.

Just for transparency, there are other issues that will need to be investigated before we get to this, but we'll be tracking this issue!
