### ISSUE TITLE
Shopify afterAuth hook not registering webhooks

### ISSUE THREAD

**Issue by jadelynhoop** [Shopify/shopify-app-js#761]
# Issue summary
From my understanding of the docs, the afterAuth hook should be registering webhooks defined in the App config, however this doesn't seem to be running.
https://shopify.dev/docs/api/shopify-app-remix/v1/guide-webhooks

- `@shopify/shopify-api` version: "^9.0.1"
- Node version: v21.6.2
- Operating system: MacOS 13.2.1 (22D68)

```
const shopify = shopifyApp({
  ... standard remix template code skipped ...
  webhooks: {
    APP_UNINSTALLED: {
      deliveryMethod: DeliveryMethod.Http,
      callbackUrl: "/webhooks",
    },
    ORDERS_CREATE: {
      deliveryMethod: DeliveryMethod.Http,
      callbackUrl: "/webhooks",
    }
  },
  hooks: {
    afterAuth: async ({ session }) => {
      console.log("DEBUGSTATEMENT afterAuth")
      shopify.registerWebhooks({ session });
    },
  },
  ... standard remix template code skipped ...
  logger: {
    level: LogSeverity.Debug,
    httpRequests: true
  },
  ... standard remix template code skipped ...
});
```

## Expected behavior
1. Webhooks defined in the app are registered, triggerable, and visible in webhook graphql query
2. My log statement should have been executed?

## Actual behavior
1. Events that should trigger the webhook are not sending webhooks
3. Graphql query should show webhook registration had happened on app install
![image](https://github.com/Shopify/shopify-api-js/assets/160537810/2ecc251a-fdd2-4387-ad0d-48898201547b)

## Steps to reproduce the problem
1. Add new webhook to Shopify App
2. Add webhook handler in webhooks.tsx
3. Query graphiql for webhook subscriptions shows the new subscriptions (empty)

**Comment by li2109** [comment]
Here's my understanding...

The afterAuth hook in a Shopify Remix app has an interesting name, though I believe it could be clearer. The term "auth" typically makes me think of login or sign-up events. As a developer, my initial assumption was that the afterAuth hook would be triggered whenever the store owner logs into the admin or becomes active online.

However, the "auth" in this context actually refers to something different. When the store owner installs App A, the app creates and persists a session in its database, along with necessary details such as the API key. This installation process that saves the session info is what "auth" refers to here as the app can now "login" (send api to Shopify via api key) to the store to get info.

In essence, the afterAuth hook runs after a store completes the authentication process during the app installation. If the app's session data is cleared from the database, the store owner would need to go through the installation process again, triggering the afterAuth hook once more.
