### ISSUE TITLE
retries > 3 throws unexpected exception - cannot read properties of undefined (reading 'headers')

### ISSUE THREAD

**Issue by RobinKemna** [Shopify/shopify-app-js#764]
# Issue summary

When running a custom store app and using the new `shopify.clients.Graphql({ session }).request()` method to query for e.g. products the library throws an exception whenever we set the retries option to something greater than 3.

I am not sure if this is an intended exception or not - imho the exception should be either more meaningful or not thrown at all.

- `@shopify/shopify-api` version: latest
- Node version: 18 LTS
- Operating system: MacOS - M3 chipset

### Exception

```
TypeError: Cannot read properties of undefined (reading 'headers')
    at throwFailedRequest ({{mypwd}}/node_modules/@shopify/shopify-api/lib/clients/common.ts:66:33)
```

### Initial Query:

```
response = await this.client.request(
      `
        #graphql
        query productQuery($after: String) {
          products(first: 150, after: $after) {
            nodes {
              ...some fields
            }
            pageInfo {
              hasNextPage
              endCursor
            }
          }
        }
      `,
      {
        variables: {
          after: null,
        },
        retries: 4,
      },
    );

```

## Expected behavior

Either throw more meaningful exception that gives a hint e.g. "configured retries to high" or respond with the proper requested data.

## Actual behavior

Throws exception without any information about the reason.

## Steps to reproduce the problem

1. install custom store app
2. create session with store name
3. create graphql client Instance
4. run any sort of query - in our case we used a simple products query for first 150 items.

**Comment by paulomarg** [comment]
Hey folks, thanks for contributing an improvement to this. We released v9.7.2 yesterday which should hopefully make it easier to spot these errors.

Please let us know if you still run into any issues!
