### ISSUE TITLE
Webhook for discount update/delete

### ISSUE THREAD

**Issue by danielfv** [Shopify/shopify-app-js#774]
Hi there,

I would be really useful to have webhooks for any updates/delete of discounts in order to keep up to date with changes on Shopify side. 

Thanks!

**Comment by lizkenyon** [comment]
Hi there 👋 

I am going to close this issue as this repository is for the javascript libraries and not the Shopify API itself.

I would recommend creating a post in the [community forum](https://community.shopify.com/c/webhooks-and-events/bd-p/events), or reaching out to Partner Support with your feature request.
