### ISSUE TITLE
Please show affected resource in GQL deprecation error

### ISSUE THREAD

**Issue by Michael-Gibbons** [Shopify/shopify-app-js#775]
## Overview/summary

Many times during development I may get deprecation notices like the one below. I'm not sure if the message is just informing me of a deprecation in the abstract or if something in my code is on the chopping block for deprecation.

In Apps > YOUR_APP > API Health the shopify admin gives me a list of exactly which properties are to be deprecated, but this is not useful for custom apps or during development.

Please include some way of getting the GQL properties which need to be updated to be compliant with the latest version of the GQL API

![image](https://github.com/Shopify/shopify-api-js/assets/13829417/1fa9ac5a-c773-4779-88f9-e5cea352e130)

**Comment by lizkenyon** [comment]
Hi folks :wave:
First of all we are so sorry that we missed this ticket. It had been removed from our tracking and we were missing all of these updates. We will do better in the future.
As some of you have suspected these warnings in the library are warnings returned by the API in the [deprecation header](https://shopify.dev/docs/api/usage/versioning#rest-api-deprecation-practices). And then the library logs them.
I think you are bringing up very valid concerns about the quality of these error messages, and how better quality error messages would help you to solve these problems more quickly. I am passing on this feedback to the product team.
If you are working on a public app I would also recommend using the insights found in the partner dashboard as they may provide more detail.
Thanks again for your patience.

**Comment by Michael-Gibbons** [comment]
WOO DREAMS REALLY DO COME TRUE

Thank you @lizkenyon 

My dreams are alive, my heart is aflutter with the possibilities, and I am floating on clouds made of cream.

**Comment by Michael-Gibbons** [comment]
![image](https://github.com/Shopify/shopify-app-js/assets/13829417/4e080940-602a-411d-b28c-af5778a80d6f)
Bump
