### ISSUE TITLE
scope column with 255 chars is not enough 

### ISSUE THREAD

**Issue by rhebekka** [Shopify/shopify-app-js#78]
When having a few `unauthenticated_*` scopes the 255 limit is not enough. and cause the app install to fail

- `@shopify/shopify-app-*` package and version: 1.0.1

## Expected behavior

no crash

## Actual behavior

crash when trying to save the scope string into the DB

## Steps to reproduce the problem

1. add a few scopes `unauthenticated_` to the App
2. install the app
3. crash when trying to save the scope string into the DB

**Comment by stwonary** [comment]
Error message:

```
 Failed to complete OAuth with error: Error: Data too long for column 'scope' at row 1
```
