### ISSUE TITLE
GraphQL Admin Codegen import types throwing TS error

### ISSUE THREAD

**Issue by daweido** [Shopify/shopify-app-js#798]
# Issue summary

Using [@shopify/admin-api-client](https://github.com/Shopify/shopify-app-js/blob/main/packages/api-clients/admin-api-client/#readme) with codegen. However, I have this error on my `admin.generated.d.ts`:

```
A declaration file cannot be imported without 'import type'. Did you mean to import an implementation file './admin.types' instead?ts(2846)
```

Before opening this issue, I have:

- [x] Upgraded to the latest version of the relevant packages
  - `@shopify/*` package and version:
  - Node version:
  - Operating system:
- [x] Set `{ logger: { level: LogSeverity.Debug } }` in my configuration, when applicable
- [x] Found a reliable way to reproduce the problem that indicates it's a problem with the package
- [x] Looked for similar issues in this repository
- [x] Checked that this isn't an issue with a Shopify API
  - If it is, please create a post in the [Shopify community forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) or report it to [Shopify Partner Support](https://help.shopify.com/en/support/partners/org-select)

I have followed the example given from the [@shopify/admin-api-client GraphQL codegen section](https://github.com/Shopify/shopify-app-js/tree/main/packages/api-clients/admin-api-client#typing-variables-and-return-objects). 

When opening my the file `admin.generated.d.ts` I have this error:

```
A declaration file cannot be imported without 'import type'. Did you mean to import an implementation file './admin.types' instead?ts(2846)
```

I have tried changing the config to this:

```
import { ApiType, pluckConfig, preset } from '@shopify/api-codegen-preset';

const config = {
  // For syntax highlighting / auto-complete when writing operations
  schema: 'https://shopify.dev/admin-graphql-direct-proxy',
  documents: ['./src/**/*.ts', '!./node_modules/**'],
  projects: {
    default: {
      // For type extraction
      schema: 'https://shopify.dev/admin-graphql-direct-proxy',
      documents: ['./src/**/*.ts', '!./node_modules/**'],
      extensions: {
        codegen: {
          // Enables support for `#graphql` tags, as well as `/* GraphQL */`
          pluckConfig,
          generates: {
            './__generated__/admin.schema.json': {
              plugins: ['introspection'],
              config: { minify: true },
            },
            './__generated__/admin.types.d.ts': {
              plugins: ['typescript', 'typescript-resolvers'],
            },
            './__generated__/admin.generated.d.ts': {
              preset: {
                ...preset,
              },
              plugins: ['typescript-operations', 'typed-document-node'],
              presetConfig: {
                apiType: ApiType.Admin,
              },
              config: {
                useTypeImports: true,
              },
            },
          },
        },
      },
    },
  },
};

export default config;
```

Which should work, but I still have the same problem. This does not allow me to run my application. I can change it manually but I would have to do so every time I run codegen.

## Expected behavior

What do you think should happen?

Having generated files which work out of the box.

## Actual behavior

What actually happens?

A Typescript error on an import.

## Steps to reproduce the problem

1. Create a GraphQL Query
2. Copy the codegen config using the shopifyApiProject function
3. Generate codegen
4. Open the `admin.generated.d.ts`.
5. Witness the TS error

**Comment by matteodepalo** [comment]
Hi @daweido, thank you for opening this issue, we'll take a look 👍

**Comment by pauldraper** [comment]
Has anybody been able to use this?

I don't get how they have...but I'm open to suggestions!

**Comment by frandiox** [comment]
Bumping a dependency to get the fix in this monorepo: https://github.com/Shopify/shopify-app-js/pull/863
