### ISSUE TITLE
App Proxy not always sending `x-ip-metadata` and `x-shop-domain` headers since end of April

### ISSUE THREAD

**Issue by darrynten** [Shopify/shopify-app-js#867]
# Issue summary

Before **April 22nd** the app proxy consistently sent through `x-ip-metadata` and `x-shop-domain` headers in every App Proxy request.

Since that date the rate at which these headers come through in requests has been in a steady decline, which is affecting apps that rely on information provided by these headers.

## Expected behavior

The `x-ip-metadata` and `x-shop-domain` headers should be available on all requests coming through the App Proxy

## Actual behavior

The headers are missing in some cases, it was around 10% on the 22nd of April, now it's the majority of the calls that are missing this info.

## Steps to reproduce the problem

1. Make a call through the app proxy, logging all headers
2. You will see the `x-ip-metadata` and `x-shop-domain` are not always present

## Debug logs

The `x-ip-metadata` value looks like this normally:

```
asn:12345;anon:1;anonVpn:0;hostProvider:1;pubProxy:0;torExit:0;countryCode:BG;regionCode:22;regionNameBase64:U29maWEtQ2FwaXRhbA==;subRegionCode:;subRegionNameBase64:;cityNameBase64:U29maWE=;postalCode:10000;timeZone:Europe\/Sofia;lat:12.34567;long:34.56789;ssbipAnon:0;ssbipAnonVpn:0;ssbipHostProvider:0;ssbipPubProxy:0;ssbipTorExit:0
```

The `x-shop-domain` normally contains the shop domain. This isn't too much of a problem as it comes in the URL params.

**Comment by lizkenyon** [comment]
Hi there 👋 

I flagged this with the team that owns app proxies! 
I am going to close this issue as this doesn't seem to be a bug with this library.

**Comment by darrynten** [comment]
@lizkenyon which repo is for the app proxy team?

**Comment by lizkenyon** [comment]
Hey @darrynten 

Unfortunately there is no public App Proxy repo, as the code for this is not public. I have reached out to the team internally and flagged your community forum post to them.

**Comment by darrynten** [comment]
@lizkenyon how can I get an update on this issue?

**Comment by degemenc** [comment]
Up! Having the same issue

**Comment by darrynten** [comment]
@degemenc maybe add a comment here: https://community.shopify.com/c/online-store-and-theme/app-proxy-not-always-sending-x-ip-metadata-header-since-end-of/m-p/2564525#M10460

Also send a partner support query, I've got a whole back-and-forth going with them about this, pretty sure it's just lip service and they have no intention of actually restoring this functionality but if enough of us ask then who knows what can happen.

**Comment by darrynten** [comment]
@degemenc I heard back from them, it's not gonna happen, header is gone for good 😢

**Comment by degemenc** [comment]
😔 thanks for the update
