### ISSUE TITLE
Simple sample 

### ISSUE THREAD

**Issue by 7ynk3r** [Shopify/shopify-app-js#872]
## Overview/summary

Can you improve your documentation? Most people don't care about all the options and API if they cannot simply authenticate **successfully**. Can you add a code sample E2E do to exactly that? 

Currently you have this, which is trying to help but it doesn't. You still need something else to know if your creds work
```
import '@shopify/shopify-api/adapters/node';
import {shopifyApi, LATEST_API_VERSION} from '@shopify/shopify-api';
import express from 'express';

const shopify = shopifyApi({
  // The next 4 values are typically read from environment variables for added security
  apiKey: 'APIKeyFromPartnersDashboard',
  apiSecretKey: 'APISecretFromPartnersDashboard',
  scopes: ['read_products'],
  hostName: 'ngrok-tunnel-address',
  ...
});

const app = express();
```

🙏

**Comment by lizkenyon** [comment]
Hi there 👋 

Thank you for your feedback! 

A couple of questions for you to help us best figure out our short comings, and how I can best direct you to the appropriate  place for next steps!

1) What libraries are you currently trying to use? (It looks like just shopify-api? Not shopify-app-express or shopify-app-remix?)
2) How did you discover this package? Google search? Or did you come from documentation from [Shopify.dev?](https://shopify.dev/docs/apps/getting-started/create) (This info can help us optimize the wayfinding of our documentation.)



If you are just getting started with Shopify App Development I would recommend starting out with the [Create an app](https://shopify.dev/docs/apps/getting-started/create) and [Build a Shopify app using Remix](https://shopify.dev/docs/apps/getting-started/build-qr-code-app?framework=remix) tutorials. This is our recommended stack for building apps, and has the most documentation. 

If you don't want to use Remix, we do have further example code for express. I believe [this example](https://github.com/Shopify/shopify-app-js/blob/main/packages/apps/shopify-app-express/README.md) of using the shopify-app-express library could be what you are looking for.
