### ISSUE TITLE
How do you create an article

### ISSUE THREAD

**Issue by 7ynk3r** [Shopify/shopify-app-js#873]
I'm trying to create an article using APIs (any will do) in NodeJS. Can you indicate how to achieve this? The docs don't help much and chatgpt, perplexity nor gemini can help. I'd really appreciate an E2E example. I already have API keys for storefront & admin with all the scopes.

For context, 

I tried using cURL 
```
curl -X GET "https://your-development-store.myshopify.com/admin/api/2024-01/articles/authors.json" \
-H "X-Shopify-Access-Token: {access_token}"
```
without success with all token
```
{"errors":"[API] Invalid API key or access token (unrecognized login or wrong password)"}%                                                                                                  
```

I tried gql 
```
curl -X POST \
  https://{shop}.myshopify.com/admin/api/2024-04/graphql.json \
  -H 'Content-Type: application/json' \
  -H 'X-Shopify-Access-Token: {access_token}' \
  -d '{
    "query": "query {
      products(first: 5) {
        edges {
          node {
            id
            handle
          }
        }
        pageInfo {
          hasNextPage
        }
      }
    }"
  }'
```
and got 
```
Bad request
```

**Comment by 7ynk3r** [comment]
If someone else ends up here better use the non-official 

https://github.com/MONEI/Shopify-api-node

**Comment by lizkenyon** [comment]
Hi there 👋 

In the future questions about how to make API calls in general are best suited for the [Shopify Community forums.](https://community.shopify.com/c/graphql-basics-and/bd-p/graphql-basics-and-troubleshooting) 

For this specific example can you confirm that you are replacing `https://your-development-store.myshopify.com` with the URL of your store and `{access_token}` with the access token of your app? 

If you want to explore the Shopify Admin and Storefront APIs you may also want to checkout the[ Graphiql explorer](https://shopify.dev/docs/apps/tools/graphiql-admin-api).
